---
title: "ggplot2练习" 
subtitle: '描述与探索'
author: ' '
date: ' '
output:
  bookdown::html_document2:
    toc: true
    theme: united
slug: ggplot
## bookdown themes:https://bookdown.org/yihui/bookdown/theming.html
---

本文链接：

<https://xsong.ltd/archives/ggplot/ggplot2prac>

# 笔记

+ 在`aes`函数里面的参数，如`fill`、`color`、`shape`，控制的是图形的映射对象。它将特定变量映射为统计图形的特定元素。而`+`后面的图形函数中的参数，仅仅是图形的附加属性。无法根据特定变量变化。


# 学习资源

[如何使用ggplot2?](https://mp.weixin.qq.com/s/mlfCRrd0CMzoYpuCSqsVtQ)

[用局部加权回归散点平滑法观察二维变量之间的关系](https://cosx.org/2008/11/lowess-to-explore-bivariate-correlation-by-yihui)

# 二维密度图

```{r,message = F, comment = NA,warning = F,cache = T,fig.align='center',out.width ='100%',fig.asp=0.6}
library(ggplot2)
library(dplyr)
library(plyr)
library(readxl)
library(modelr)
library(easyGgplot2)
library(reshape2)
library(rgdal)
`%>%` <- magrittr::`%>%`

data(diamonds)
knitr::kable(head(diamonds),caption="数据概要",align='c')
#原始变量关系
ggplot(diamonds, aes(carat,price)) +
geom_bin2d() +
facet_wrap(~cut, nrow = 2)
#y变量取对数
ggplot(diamonds, aes(log(carat),price)) +
geom_point() +
facet_wrap(~cut, nrow = 2)
#x变量取对数
ggplot(diamonds, aes(carat,log(price))) +
geom_bin2d() +
facet_wrap(~cut, nrow = 2)
#都取对数，最终成为线性关系。
ggplot(diamonds, aes(log(carat), log10(price))) +
geom_bin2d(bins = 100) +
facet_wrap(~cut, nrow = 2)
```

# 抽样散点图

```{r,message = F, comment = NA,warning = F,cache = T,fig.align='center',out.width ='80%',fig.asp=0.7}
library(haven)
setwd("E:/R_codes/capplot")
X2010 <- read_dta("2010.dta")
xy <- read_dta("id.dta")
hho <- read_dta("aggregrate.dta")
nrow(hho)
set.seed(13)#设置随机数种子
sample <- sample(1:nrow(hho),600,replace = F)#抽取600个样本
hhosampled <- hho[sample,]#抽取

scattered <- ggplot(hho,aes(x=agem,y=inc,group=type,shape=type,color=type,weight=fswt_nat)) +
  ylim(0, 20000) +
  labs(title = " ",x = "年龄",y = "人民币(元）") +
  geom_smooth(span = 10,size=1.5) + 
  geom_point(data = hhosampled, alpha = 4/7,size = 2.5 )  +
  annotate("text", x = 70, y = 200, label="数据来源：CFPS,正常散点", size = 4) + #注解
  theme(legend.position = c(0.9,0.9))#图例位置
scattered
```

```{r ,message = F, comment = NA,warning = F,cache = T,fig.align='center',out.width ='80%',fig.asp=0.6}
i <- ggplot(economics, aes(date, unemploy))
i + geom_area()

i + geom_line()

```

# 模型可视化

```{r ,message = F, comment = NA,warning = F,cache = T,fig.align='center',out.width ='80%',fig.asp=0.8}
set.seed(711)
x = seq(0, 4, length = 100)
y = -x + jitter(rep(1:5, each = 20), 2)
z = rep(1:5, each = 20)
z <- as.factor(z)
moto <- data.frame(x,y,z)
#ols无控制变量
ggplot(moto, aes(x, y)) +
  geom_point(aes(color = z),size=3) +
  geom_smooth(method='lm',se=F)
```

## 分面

```{r ,message = F, comment = NA,warning = F,cache = T,fig.align='center',out.width ='80%',fig.asp=0.6}
ggplot(moto, aes(x, y)) +
  geom_point(aes(color = z)) +
  facet_wrap(~z, nrow = 2) +
  geom_smooth(method='lm',se=F)
```

## 分组

+ 使用[`modelr`](https://r4ds.had.co.nz/model-basics.html)包进行模型拟合

```{r,message = F, comment = NA,warning = F,cache = T,fig.align='center',out.width ='80%',fig.asp=0.8}
#不同组拟合不同的模型
ggplot(moto, aes(x, y,group=z)) +
  geom_point(aes(color = z),size=3) +
  geom_smooth(method='lm',se=F)

mod1 <- lm(y ~ x + z,data = moto)
grid <- moto %>%
data_grid(x,z) %>%
gather_predictions(mod1)
knitr::kable(head(grid),caption="数据概要",align='c')
#不同组拟合同一个模型，控制组z              
ggplot(moto, aes(x, y,group=z)) +
  geom_point(aes(color = z),size=3) +
  geom_line(data = grid, aes(y = pred,x=x),size=0.8,color='blue') +
  ylim(0.5,2)


```

# 地图绘制

+ 不会分面(`facet_wrap`)者的笨办法，使用`ggplot2.multiplot`手动合并图形

```{r,echo=F,message = F, comment = NA,warning = F,cache = T,fig.align='center',out.width ='100%'} 
rm(list=ls())
china_map_data <- read_dta("E:/R_codes/maps/nomissing/chnprovcd.dta")

mapdata <- read_excel("E:/R_codes/ggplot2map/geodata0131.xlsx")
mapdata <- as.data.frame(mapdata)
mapdata <- select(mapdata,-(NAME)) #reverse selection
china_data <- join(china_map_data, mapdata, type="full")

china_data <- select(china_data,long,lat,group,out12,in12,out14,in14,out16,in16)

out12 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= out12)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") + 
  coord_map("polyconic") +  
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 

in12 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= in12)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") +  
  coord_map("polyconic") +  
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 

out14 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= out14)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") + 
  coord_map("polyconic") + 
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 

in14 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= in14)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") +  
  coord_map("polyconic") + 
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = c(0.9,0.6),
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 

out16 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= out16)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") + 
  coord_map("polyconic") +   
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 

in16 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= in16)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") +  
  coord_map("polyconic") +     
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 
```

```{r,message = F, comment = NA,warning = F,cache = T,fig.align='center',out.width ='100%'} 
#devtools::install_local("C:/Users/xsong/Desktop/easyGgplot2-master.zip")
ggplot2.multiplot(out12,in12,out14,in14,out16,in16, cols=2)
```

## 数据长宽转换

+ 使用[`reshape2`](https://seananderson.ca/2013/10/19/reshape/)进行数据长宽转换。

+ 使用[`facet_wrap`](https://ggplot2.tidyverse.org/reference/facet_wrap.html)进行分面

[`facet_grid()`介绍](https://ggplot2.tidyverse.org/reference/facet_grid.html#examples)

```{r,message = F, comment = NA,warning = F,cache = T,fig.align='center',out.width ='100%'} 
long <- melt(china_data, id=c("long", "lat","group"))

ggplot(long, aes(x = long, y = lat, group = group,fill= value)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") +
  coord_map("polyconic") +  
  facet_wrap(~variable,nrow = 3) +
  labs(x='经度',y='纬度') +
  theme(legend.title=element_blank()) +   
  theme_bw()

```

## 气泡地图

```{r,message = F, comment = NA, warning = F,cache = T,fig.align='center',out.width ='100%'} 
bottom  <- readOGR(dsn = "E:/R_codes/maps/CHN_adm/CHN_adm2.shp",stringsAsFactors=F)

bottomdata <- fortify(bottom)         
x <- bottom@data          
xs <- data.frame(x,id=seq(0:344)-1)        

china_map <- join(bottomdata, xs, type = "full")          

fills <- read_excel("E:/R_codes/maps/pointmap/citydis.xlsx")

china_map <- join(china_map,fills, type = "full")   
point <- china_map
point <- na.omit(point)
midpos <- function(x) mean(range(x,na.rm=T)) 
centres <- ddply(china_map,.(NAME_2),colwise(midpos,.(long,lat)))
center <- join(centres,fills, type = "full") 
center  <- na.omit(center)

ggplot(china_map,aes(x=long,y=lat)) + 
  geom_polygon(aes(group = group),fill="white",color="black",size=0.1) + 
  geom_point(mapping = aes(x=long, y=lat, size = freq),data = center, colour = "steelblue") +
  coord_map("polyconic") +
  labs(x='经度',y='纬度') +
  theme(legend.title=element_blank()) +   
  theme_bw()

```

# 主题

```{r,message = F, comment = NA, warning = F,cache = T,fig.align='center',out.width ='100%'} 
ggplot(moto, aes(x, y)) +
  geom_point(aes(color = z),size=3) +
  geom_smooth(method='lm',se=F) +
  theme_bw()

ggplot(moto, aes(x, y)) +
  geom_point(aes(color = z),size=3) +
  geom_smooth(method='lm',se=F) +
  theme_grey()

ggplot(moto, aes(x, y)) +
  geom_point(aes(color = z),size=3) +
  geom_smooth(method='lm',se=F) +
  theme_classic()

ggplot(moto, aes(x, y)) +
  geom_point(aes(color = z),size=3) +
  geom_smooth(method='lm',se=F) +
  theme_light()
```































