---
title: "个人陈述草稿"
author: "[宋骁](https://xsong.ltd/zh/)"
date: '`r Sys.Date()`'
output:
  bookdown::html_document2:
    toc: true
    theme: united
slug: ps
---
+ 术语用括号标出

---

今天的日期是`r Sys.Date()`

# QMSS

作为一名社会学系本科生。我在本科期间修读了若干课程，如性别社会学、人口与社会、经济社会学等，这些课程均要求提交一份经验性研究。在性别社会学课程上，我接触到了男女不平等这一社会现象，我刚结婚的表姐也向我们家人透露过她在职场上遭到的不平等待遇，很多用人单位在招女员工的时候，会在面试阶段就询问有没有生育的打算，并且很多岗位都明确只招男生。带着对这个问题的兴趣，我访谈了我的表姐。我在这个过程中学会了如何独立做一个完整的研究，如进行文献综述、收集经验材料等。访谈法代表的定性研究帮助我直观地从感性层面了解社会现象。

在课程中我对于研究方法是困惑的。因为我不能确定访谈法能保证研究的外部有效性。如果一次为基础的推断和总结都不具有推广性，社会学的研究就起不到了解社会和改变社会的目的。定量研究是否能够为社会学研究提供更科学的方法呢？带着这个疑问，我选修了卿石松老师的定量方法课。在学习了基本的概率统计和回归分析知识后。我发现统计模型的有趣之处：统计模型不仅能把握当下的相关关系，还能预测未来。比如，通过一个人的教育、家庭、婚姻等变量预测收入。此外，这些关系还能通过可视化展示出来，让非专业背景的人也能直观地理解社会学的研究成果，扩大社会学研究的影响力。这让我爱上了数据分析！为了进一步探究统计方法在社会学中的应用，我还在大二学年自学了R语言和数据可视化。

在这门课结束之后，我跟随卿石松老师将之前的性别不平等题目扩展成为一个定量研究。我讨论了性别观念、工作时间、家务劳动时间对夫妻双方的婚姻满意度的影响。在做这个研究的过程中，我学习了方差分析(Analysis of Variance,简称ANOVA)、线性回归(Linear Regression)、广义线性模型(Generalized linear model)等统计学方法。我在论文中注重应用统计图形(Statistical Graphics)进行交流。但在得出结论的时候，导师指出未经过严格反事实实验设计的回归分析不足以得出可靠的因果关系。我对于定量研究的因果推断问题陷入了沉思。我选修了李强老师的课程。

在李强老师的课上，我学习了人口学导向的以生存分析为主的数据分析方法。在这门课的课程作业中，我延续了对婚姻与社会不平等主题的探索。我讨论了外貌(apperance)作为一种“非认知能力”(non-cognitive ability)对婚姻行为的影响。我的null hypothesis是外表能帮助人们更快地走入婚姻关系， 通过数据分析我最终reject the null hypothesis。经济和教育水平的门当户对才是决定婚姻的第一因素。这种婚姻匹配模式也促进了阶层的固化。在这个研究中，我应用生存分析(Survival Analysis)方法，将结婚事件的发生事件纳入考虑。生存分析通过分析促使不同状态的转换(生到死、未婚到已婚)的时间效应来理解社会，它拓展了我对统计方法的认识。很多结果并非由一两个单独的原因来决定，而可能随时间推移自然发生。现实世界的复杂性让我意识到之前掌握的统计知识是远远不够的。我决定更深入地学习因果推断的方法。

大三年级，我选修了因果推断框架下的计量经济学(Econometrics)课程。这些奇妙的实验设计能够剥除其他混淆因素的影响，单独估计自变量对因变量的纯因果效应。比如，双重差分(difference-in-difference)模型引入了自然实验(natural experiment)设计，巧妙地估计出因果效应(Causal Effect)。在学习计量(Metrics)课程的同时，它们的思想深深吸引了我。在学年论文选题的时候。我决定使用面板数据(Panel Data)的方法，讨论土地流转行为对中国农户的家庭收入的影响。同时，我还使用了分位数回归(Quantile regression)的办法估计社会不平等问题。

为了进一步了解机器学习算法以及编程语言以及为QMSS项目做准备。我报名参加了一个在线培训项目。这个项目要求学员使用Python和银行历史数据建立[信用卡申请评分模型](https://xsong.ltd/archives/pandas/scorecard_en)。在这期间，我学习了几个较为主流的机器学习算法。如决策树(classification and regression trees)、随机森林(random forest)、AdaBoost等。我阅读了《An Introduction to Statistical Learning with Applications in R》一书。我这些模型能够很好地对个体的状况进行预测。它们能够通过大量学习器的组合掌握高维变量(High dimensional variables)的非线性关系，提取数据中潜藏的大量信息。同时，交叉验证(Cross-Validation)的方法能够客观评估模型在新数据集的表现。这使得机器学习模型拥有比传统统计学模型更为强大的预测和泛化能力。

我着迷于机器学习模型思路的精致和巧妙。我萌生了使用机器学习算法写作毕业论文的想法。目前我正在研究初中生数学成绩的预测方法。我使用XGBoost算法训练模型，通过学生个人、家长、班级、学校多方面的数据预测学生的数学成绩，并且计算出每个变量的重要性。

为了更好地展示和交流我的作品。也出于对开源的数据科学社区的贡献。我学习了基本的网页技术(html、CSS、JavaScript)。使用Github和Netlify部署并开通了我的个人网站[xong.ltd/en](https://xsong.ltd/en/)。它使我能在几分钟内将数据分析结果分享到网络上和大家交流。这个网站还在Github上开源了所有的源代码。它实现了可重复性研究和开源的目标。

未来我计划成为一名计算社会科学家(Computational Social Scientist)。我将继续深入了解Python和R语言。将机器学习知识引入到社会科学领域。以往关于社会分层与不平等的研究大多使用传统的定量模型。而我想使用机器学习模型研究以往的问题。未来我想使用诸如爬虫、文本分析、自然语言处理(Natural Language Processing)的高级方法研究非结构化数据。QMSS的课程和教学设置将是我达成目标的不可或缺的一环。


---

# LSE

作为一名社会学系本科生。我在本科期间修读了若干课程，如性别社会学、人口与社会、经济社会学等，这些课程均要求提交一份经验性研究。在性别社会学课程上，我接触到了男女不平等这一社会现象，我刚结婚的表姐也向我们家人透露过她在职场上遭到的不平等待遇，很多用人单位在招女员工的时候，会在面试阶段就询问有没有生育的打算，并且很多岗位都明确只招男生。带着对这个问题的兴趣，我访谈了我的表姐。我在这个过程中学会了如何独立做一个完整的研究，如进行文献综述、收集经验材料等。访谈法代表的定性研究帮助我直观地从感性层面了解社会现象。

在课程中我对于研究方法是困惑的。因为我不能确定访谈法能保证研究的外部有效性。如果一次为基础的推断和总结都不具有推广性，社会学的研究就起不到了解社会和改变社会的目的。定量研究是否能够为社会学研究提供更科学的方法呢？带着这个疑问，我选修了卿石松老师的定量方法课。在学习了基本的概率统计和回归分析知识后。我发现统计模型的有趣之处：统计模型不仅能把握当下的相关关系，还能预测未来。比如，通过一个人的教育、家庭、婚姻等变量预测收入。此外，这些关系还能通过可视化展示出来，让非专业背景的人也能直观地理解社会学的研究成果，扩大社会学研究的影响力。这让我爱上了数据分析！为了进一步探究统计方法在社会学中的应用，我还在大二学年自学了R语言和数据可视化。

在这门课结束之后，我跟随卿石松老师将之前的性别不平等题目扩展成为一个定量研究。我讨论了性别观念、工作时间、家务劳动时间对夫妻双方的婚姻满意度的影响。在做这个研究的过程中，我学习了方差分析(Analysis of Variance,简称ANOVA)、线性回归(Linear Regression)、广义线性模型(Generalized linear model)等统计学方法。我在论文中注重应用统计图形(Statistical Graphics)进行交流。但在得出结论的时候，导师指出未经过严格反事实实验设计的回归分析不足以得出可靠的因果关系。我对于定量研究的因果推断问题陷入了沉思。我选修了李强老师的课程。

在李强老师的课上，我学习了人口学导向的以生存分析为主的数据分析方法。在这门课的课程作业中，我延续了对婚姻与社会不平等主题的探索。我讨论了外貌(apperance)作为一种“非认知能力”(non-cognitive ability)对婚姻行为的影响。我的null hypothesis是外表能帮助人们更快地走入婚姻关系， 通过数据分析我最终reject the null hypothesis。经济和教育水平的门当户对才是决定婚姻的第一因素。这种婚姻匹配模式也促进了阶层的固化。在这个研究中，我应用生存分析(Survival Analysis)方法，将结婚事件的发生事件纳入考虑。生存分析通过分析促使不同状态的转换(生到死、未婚到已婚)的时间效应来理解社会，它拓展了我对统计方法的认识。很多结果并非由一两个单独的原因来决定，而可能随时间推移自然发生。现实世界的复杂性让我意识到之前掌握的统计知识是远远不够的。我决定更深入地学习因果推断的方法。

大三年级，我选修了因果推断框架下的计量经济学(Econometrics)课程。这些奇妙的实验设计能够剥除其他混淆因素的影响，单独估计自变量对因变量的纯因果效应。比如，双重差分(difference-in-difference)模型引入了自然实验(natural experiment)设计，巧妙地估计出因果效应(Causal Effect)。在学习计量(Metrics)课程的同时，它们的思想深深吸引了我。在学年论文选题的时候。我决定使用面板数据(Panel Data)的方法，讨论土地流转行为对中国农户的家庭收入的影响。同时，我还使用了分位数回归(Quantile regression)的办法估计社会不平等问题。

为了进一步了解机器学习算法以及编程语言以及为QMSS项目做准备。我报名参加了一个在线培训项目。这个项目要求学员使用Python和银行历史数据建立[信用卡申请评分模型](https://xsong.ltd/archives/pandas/scorecard_en)。在这期间，我学习了几个较为主流的机器学习算法。如决策树(classification and regression trees)、随机森林(random forest)、AdaBoost等。我阅读了《An Introduction to Statistical Learning with Applications in R》一书。我这些模型能够很好地对个体的状况进行预测。它们能够通过大量学习器的组合掌握高维变量(High dimensional variables)的非线性关系，提取数据中潜藏的大量信息。同时，交叉验证(Cross-Validation)的方法能够客观评估模型在新数据集的表现。这使得机器学习模型拥有比传统统计学模型更为强大的预测和泛化能力。

我着迷于机器学习模型思路的精致和巧妙。我萌生了使用机器学习算法写作毕业论文的想法。目前我正在研究初中生数学成绩的预测方法。我使用XGBoost算法训练模型，通过学生个人、家长、班级、学校多方面的数据预测学生的数学成绩，并且计算出每个变量的重要性。

为了更好地展示和交流我的作品。也出于对开源的数据科学社区的贡献。我学习了基本的网页技术(html、CSS、JavaScript)。使用Github和Netlify部署并开通了我的个人网站[xong.ltd/en](https://xsong.ltd/en/)。它使我能在几分钟内将数据分析结果分享到网络上和大家交流。这个网站还在Github上开源了所有的源代码。它实现了可重复性研究和开源的目标。

未来我计划成为一名计算社会科学家(Computational Social Scientist)。我将继续深入了解Python和R语言。将机器学习知识引入到社会科学领域。以往关于社会分层与不平等的研究大多使用传统的定量模型。而我想使用机器学习模型研究以往的问题。未来我想使用诸如爬虫、文本分析、自然语言处理(Natural Language Processing)的高级方法研究非结构化数据。QMSS的课程和教学设置将是我达成目标的不可或缺的一环。

这个项目有许多我感兴趣的课程，它们是帮助我实现职业规划和专业训练的不可或缺的资源。如Blake Miller的Special Topics in Quantitative Analysis: Quantitative Text Analysis课程能帮助我使用文本分析的方法讨论社会不平等问题、
Blake Miller的Applied Machine Learning for Social Science课程将帮助我进一步理解机器学习与社会科学的融合。它灵活的课程组合使我可以选择自己感兴趣的社会学主题，我的加入同样能为这个项目带来多样性，我所学到的定量分析方法能够运用到中国研究中去。伦敦作为一个国际大都市，同样有利于技术的交流与思维的碰撞。





<!---
未来我愿意进入互联网行业工作。在之后的职业生涯中，我希望能够进入互联网或咨询行业从事数据分析或数据科学方面的工作。我将进一步着眼于数据在业务场景中的应用。我感兴趣的是如何让数据产生真正的商业价值。而这需要对具体业务场景的深入了解。在艾瑞咨询公司的实习经历使我了解到真实的商业界如何在使用什么样的算法和模型。在这个公司中，我接触到了大数据架构。我们在工作中会大量使用爬虫(Python)和自然语言处理等方面的知识。由于我之前缺少这方面的训练，希望能够在NLP方面取得进步。



尽管计量经济学的因果推断框架对于理解变量的机制有着十分重要的用途，但这些方法对事件的预测效果并不好。一个问题深深困扰着我：为什么在因果关系被知晓后却仍然无法对世界做出很好的预测？

后来我转而自学机器学习框架下的统计模型。

我申请...学校的原因是。这个项目旨在于

。由于如今各行各业的公司都会在业务中收集大量的数据，我希望能在真实的业务场景中让数据产生价值。并且能将数据思维引入到我今后将会进入的行业中去。

在政治系做RA

暑假在新闻学系是TA

学生社团的副社长

QMSS 中间可以申CPT。在学校的话不需要。

*Computational Social Scientist* Story Line 

Research Design的重要性。 想学Experimental Design

machine learning的东西 信用卡模型

99%的同学没啥学术成果

Research Interest集中在*不平等*领域。

把之前的经历串起来 每段经历都是用来服务career goal的。

在某一节课上对这个感兴趣。稍微提一下。从*机器学习*的角度研究之前感兴趣的问题。

稍微偏后面写这个项目能给我提供的东西。

通过*术语*来体现自己的专业。可以保留一些很具体的句子。每段经历怎么引向了下一段经历。这段经历激发了什么思考。希望把这种方法。每一段的首句开门见山总结下。不要拐来拐去。对社会不平等的感悟。

日期：趁热打铁，列提纲。快的话，两到三周。

哥大Graduate School。TOEFL。

DDL是2.13。

自己的经历非常有特色。
--->


# BA文书

<!--
“颜值”真的重要吗？——相貌因素对初婚风险的影响
在我大二的时候，我曾做过一个这样的社会研究，相貌因素对初婚风险影响有多大，在进行实验的量化分析之前，实验的结果基本已经被大多人所锁定---毫无疑问相貌对男女关系会存在十分大的影响，然而经过层层数学模型与分析统计后，我得到了一个出乎意料的结论：相貌因素并不能影响中国人进入初婚的时间，美丽外貌在婚姻市场的作用易被年龄效应和同质婚效应掩盖；论文的结论引起了一定的关注，也被选入中国社会学年会，而我也从此被数据的力量所深深折服，决定要在数据领域展开更深度的学习与研究

- 强调已经满足了先修课
在大学四年间，我以年纪前10%的成绩完成了ba的先修课，包括回归分析，概率论、stata、spss等，并主导了多次强数据导向的社会研究，均取得一定成果（eg）

--->


## 兴趣起源段

学术背景 职业背景

我是谁

为啥对这个感兴趣？

论据：为啥我可以。使用经历

短期 长期目标

为啥是这个学校，不是其他学校，双向选择的匹配。

Why School

相貌对初婚时间的影响。很多申请者不具备这个话题。本科早期做的。时间点能够串得上。

本来对社会学研究。

*矛盾点？*。相貌毫无疑问很重要。结果被锁定。被数据讲故事后。结论出乎意料。相貌不能影响。很多东西不能用经验所判断。需要用数据！过渡到为什么要申请研究生。

引入数据分析高度相关的例子。

数据改变了很多人的预先判断。社会学

不要写自己的模型。经过数据模型和分析统计后。balabala。
结论写出来。论文的结论引起一定关注。论文被印。我被数据分析的魅力深深折服。

为什么要学这个专业

我的年级排名为前%几。包括统计学、概率论、线性代数。

## 第二段

继续的社会研究。

土地流转研究-和实习经历

对颜值的研究之后。进行了数据导向的研究。如何通过数据？

用R做了地理信息可视化。输出了什么有价值的东西。**数据分析和专业研究领域**。BA是横向限制职能的专业。**数据能力在场景中的应用: 扣题**

## 第三段

信用卡(30%)和`iresearch`(70%)。第二段1.5倍。为了进一步提升数据解决能力。侧重交代数据分析能力。用了什么工具搞模型。量化分析能力。数据专业水平。如何做特征选择、清理数据。强化讲技能点。

下一段的探索。用什么方法做了什么。取得了什么成就。对公司有什么影响。我用了机器学习。具体讲贡献。如何在商业领域应用数据分析？


## 第四段

+ 职业规划 10%

引导我产生的什么目标。希望涉及机器学习领域。通过数据挖掘产生商业价值。用数据的方式理解社会科学？毕业后进入咨询行业。打通数据导入、清理、建模、赋能商业价值。

长期目标，简写一下，最终想成为用数据推动商业智能化。

数据驱动商业决策。咨询行业的数据专家。

Data Driven 

## Why School?

为啥是这个学校，不是其他学校，双向选择的匹配。本身发展计划和项目契合点。就是想涉足机器学习领域。从事编程！Practical。想参加实践项目。这个项目和我要的是契合的。课程设置。特殊课程、机器学习、深度学习。专业的地理位置优势。**能给学院带来什么？** 数据是一个日新月异的领域。如何弥补？利用学校的校友会。从事社会工作的。组建Data Science交流会。校友会来。社会学背景可以带来对这方面的补充。个人背景对学校的补充。

## 描述挑战

>Describe a challenge related to data or analytics that you have encountered. How did you resolve this challenge, and did you succeed?
Your response should be no more than 250 words.

放iresearch。讲核心矛盾。Optional essay. 自己要

>At Johns Hopkins Carey Business School, we shape business leaders who seize opportunity, inspire change, and create lasting value. How is your future industry evolving and in what ways do you hope to inspire change and create lasting value?

明确发展方向。

往物联网进行发展。酒店。贡献的方向和自己的背景结合起来。

---


在我大二的时候，我曾做过一个这样的社会研究《“颜值”真的重要吗？——相貌因素对初婚风险的影响》(Does Appearance Attraction Really Matters? —The Effects of Attractiveness on First Marriage)。我讨论了相貌因素对中国人结婚时间的影响，在进行量化分析之前，实验的结果基本已经被大多人所锁定---毫无疑问相貌对男女关系会存在十分大的影响，然而经过严谨的统计学分析后，我得到了一个出乎意料的结论：相貌因素并不能影响中国人进入初婚的时间，美丽外貌在婚姻市场的作用易被年龄效应和同质婚效应(assortative mating effect)掩盖；论文的结论引起了一定的关注，也被选入中国社会学论坛，而我也从此被数据的力量所深深折服，决定要在数据领域展开更深度的学习与研究。数据能够科学地验证人们的常识。而经验和直觉往往是不可靠的。

在选修了更深层次的因果推断技术后。我将土地流转(Land transfer)研究作为了我的学年论文题目。在这个研究中，我将中国的土地流转数据进行了地理信息可视化。在模型方面，我使用面板数据分析(Panel Data Analysis)的方法，讨论土地流转行为对中国农户的家庭收入的影响。同时，我还使用了分位数回归(Quantile regression)的办法估计社会不平等问题。

为了进一步提升数据分析应用的能力。我在数据科学平台上(如Kaggle)和网络课程上学习了基于Python和R实现的机器学习模型。为了加强对数据和算法的理解。我参与了北京大学的在线培训项目：信用卡评分模型(credit card score)。通过使用真实的信用卡申请数据。这个数据集包含了很多信用卡申请者的个人特征，如性别、出生日期、婚姻状况和教育状况等。通过这些特征(features)预测未来可能的拖欠风险。我注重数据的特征工程问题。在做这个项目的过程中，违约客户样本过少的问题困扰了我。我通过SMOTE技术处理样本类别不平衡(class imbalanced)问题。最终获得了很好的预测准确率。

此外。我学习了基本的网页技术(html、CSS、JavaScript)。这些知识是处理非结构化数据(比如文本数据)的必要基础。使用Github和Netlify部署并开通了我的个人网站xong.ltd/en。它使我能在几分钟内将数据分析结果分享到网络上和大家交流。

为了深入了解实际业务场景中的数据分析。我去了艾瑞(iresearch)集团进行了数据分析助理的实习。我做了许多数据分析工作。包括对业务数据进行查询和分组统计（基于MySQL）。在关于著名玩具企业的研究项目中，需要分析从社交媒体中爬取的文本数据。通过对文本数据去除停止词(Stop Words)、提取词干；我得到了在特定时间段中人们对于玩具评价的主题(如好玩、有趣、配送慢、价格贵等)。通过这些反馈的主题，可以得到用户关于玩具反馈的重要信息。此外，还能够通过情感分析(sentiment analysis)的方式分析人们是否积极地评价这些产品。最后我还对社交媒体的文本数据进行了词云(Word Cloud)的可视化工作。这些工作使得玩具企业能够实时地得到用户的反馈。从而对产品的缺陷加以改进，对优点进一步贯彻。


咨询公司的实习经历让我看到了数据分析产生商业价值的可能性。我毕业后的职业目标是进入咨询公司任职。通过数据驱动商业决策，进而达到商业智能化(business intelligence)的目的。由于如今各行各业的公司都会在业务中收集大量的数据，我希望能在真实的业务场景中让数据产生价值。并且能将数据思维引入到我今后将会进入的行业中去。咨询领域的数据专家不仅需要数据科学知识还需要商业的领域知识，最终用数据推动商业智能化。

我想通过硕士阶段的学习更深入地学习数据科学，包括机器学习方法。基于Python与R的数据科学编程方法是我通过数据产生商业价值不可或缺的训练。通过数据科学和机器学习的训练，这些方法能够促进我胜任生产环境中数据分析任务。同时，一些更有挑战性的深度学习、文本挖掘和数据库的知识。其次，虽然我本科的专业是社会学。但我主动选修了线性代数、概率论与数理统计等BA先修课程。我在入学后，会利用校友会资源，组建Data Science交流会，讨论Data Science技术问题以及Kaggle平台的数据分享及交流。我的加入能为这个项目带来多样性。

---


在大学期间我参与过学院的辩论队。辩论队的生活一开始让我非常不适应。在每次打比赛的前几天需要阅读大量相关文献材料，以支持立论的观点。这往往需要睡得很晚，因此我曾一度想要放弃。有时队友之间还会因为观点的分歧而产生争吵。然而，这么做的结果是值得的。经历了严谨并充分的准备换来的往往是一场胜利。如果连队友都无法说服，那么自己的观点也同样无法战胜对手。

在辩论队的经历同样激发了我的学术热情。准备打一场辩论的过程就像一个真正的学术研究。任何一个观点都需要来自相关文献的支持。这大大加强了我对学术研究的兴趣并锻炼了我的学术能力。因为实证研究同样需要大量的数据和事实来支撑观点。此外，辩论赛也是一个考验和队友团队协作能力的过程。如果和队友没有默契，即使个人能力再强，也无法获得很好的成绩。

比如，在一次重要的校内比赛中，我们的题目是“人是否有表达偏见的自由和权利”。作为正方辩手。我们的立场处于劣势。此外，我和队友对我们的立论点产生了分歧。队友认为偏见本身具有蛊惑性，只是随着社会的进步，一些偏见成为了真理。我认为队友的立论可能会被对方抓住弱点。我的观点是：是偏见的内容而不是偏见的形式对社会有害。经过一系列文献的阅读。我的观点被队友认为最具有说服力。最后我们在比赛中打败了对手。

---

我最难忘的经历是大学二年级参加学术会议的经历。大二年级的时候我写作了关于性别观念的定量研究。为了提升和改进我的研究，我决定报名参加社会分层与流动领域的权威论坛：中国社会学分层与流动冬季论坛。这是我的第一次学术会议经历，我在参加前因为自己是本科生，需要在知名教授面前演讲而紧张。同时对于自己能力的质疑让我并不是很愿意分享自己的研究成果。

因此，我为这次会议准备了很长时间。我在会议之前仍然在不断校读和修改论文。为了控制好演讲的节奏和时间，我还模拟报告。指导老师告诉我，为了更好地展示定量分析的结果，最好使用统计图形的方法。因此我开始学习数据可视化技巧，使得统计结果更容易被理解。

我使用幻灯片进行汇报演讲。评议我的老师是人口、社会分层等领域著名的教授。虽然我的研究有很多不足，评议老师并未因为我是初出茅庐的本科生而区别对待。他们从专业角度评价了我的论文。给出了许多建设性意见。其次，在会议中途茶歇时间，教授们还和我进行了交流。和答辩时的严厉不同的是，他们积极鼓励我从事学术研究。这次经历引发了我对学术研究和数据分析的极大兴趣。因为教授们的严格要求对于日后的学术训练来说非常重要。对我来说，自己的成果能被前辈认可是很大的鼓励。这次经历之后，我越来越愿意使用清楚而规范的方式分享并展示自己的研究，让更多的人来评价我的研究。也为日后我建立个人网站奠定了基础。

在后面的研究，我非常注重老师们给我提出的专业意见，我会以尽量简明的文字阐述问题、论证观点。同时，尽量分享和公开自己的研究（如在我的个人网页上），从公开的讨论中学习并改进。

----

Brown大学有着优秀的学术资源和氛围。它能包容各种各样的学术观点与个性。作为一个坚持使用定量方法做社会研究的学生，我认为在Brown能够得到更客观的评价。而且我相信我的能够和Brown大学其他的同学和老师进行对话和交流。此外，Brown大学严肃沉静的学术气氛鼓励学生认真科研，而不仅是传授学生在社会上生存的技能。我喜欢较为安静的学术氛围，罗德岛静谧的氛围适合潜心研究学术。此外，Social Analysis and Research
(MSAR)项目提供了丰富的空间数据分析课程以供选修。如Spatial Data Analysis Techniques in the Social Sciences (SOC 2960G)。这些分析方法能够大大丰富传统的社会科学研究。由于我之前的研究(土地流转)做过相关的工作，它们是我非常感兴趣的方向。我希望自己能更进一步学习空间数据分析的方法。




class: center, middle, inverse
### Progress bar for 2018：▓▓▓▓▓▓▓▓▓▓▓▓▓▓░     97%

--------------

行业trend

数据科学能够促使发挥更大的价值。相当多的价值隐藏在海量数据中。然而，算法本身应该为人服务。数据科学项目应当服务于具体的业务需求。一个成功的数据项目不仅仅是技术的创新。更是业务与管理的成功高效的工程实施。比方说，首先需要与甲方明确用户需求、确定明确的业务目标。






