---
title: "R"
author: " "
date: " "
output:
  bookdown::html_document2:
    toc: true
    theme: united
slug: ranalysis
---

# 聚类分析

## k-means聚类

[k-means in R](https://uc-r.github.io/kmeans_clustering)

```{r delta,message = F, comment = NA,warning = F,include = T,fig.align='center',out.width ='100%',fig.asp=0.7}
#葡萄酒数据
#install.packages("rattle")
data(wine, package="rattle")
knitr::kable(head(wine))

library(cluster)
set.seed(1234)
fit.pam <- pam(wine[-1], k=3, stand=T)#3个质心
fit.pam$medoids #查看质心

c
library(fMultivar)
set.seed(1234)
df <- rnorm2d(1000, rho=0.9) #2元正态分布
df <- as.data.frame(df)
plot(df, main="Bivariate Normal Distribution with rho=0.9")

library(ggplot2)
library(cluster)
fit <- pam(df, k=2)
df$clustering <- factor(fit$clustering)#输出聚类结果变量
ggplot(data=df, aes(x=V1, y=V2, color=clustering, shape=clustering)) +
geom_point() + ggtitle("Clustering of Bivariate Normal Data")

require(graphics)
# a 2-dimensional example
x <- rbind(matrix(rnorm(100, sd = 0.3), ncol = 2),
           matrix(rnorm(100, mean = 1, sd = 0.3), ncol = 2))
colnames(x) <- c("x", "y")
(cl <- kmeans(x, 2))
plot(x, col = cl$cluster)
points(cl$centers, col = 1:2, pch = 8, cex = 2)

```


```{r a,message = F, comment = NA,warning = F,include = T,fig.align='center',out.width ='100%',fig.asp=0.6}

#班级数据
library(cluster)
Rclass=read.csv("E:/R_codes/others/Rdclass.csv",header=T)
Rclass1=Rclass[,-c(1,6,7,8)]
rownames(Rclass1)=Rclass$Name
gower_dist<-daisy(Rclass1,metric = "gower")#分类变量的聚类
#summary(gower_dist)
h <- hclust(gower_dist)
plot(h)
rect.hclust(h, k=7, border = "red")
(cn <- cutree(h, k = 7))



```

# 词云图

```{r b,message = F, comment = NA,warning = F,include = T,cache=T,fig.align='center',out.width ='100%',fig.asp=0.6}
#install.packages('wordcloud2')
#install.packages('jiebaR')
library(wordcloud2)
library(jiebaR)
text <- readLines("E:/R_codes/others/Rkws.csv",encoding = "UTF-8")
text <- text[-1] 
freq <- freq(text)
index <- order(-freq[,2]) 
order2 <- freq[index, ]
wordcloud2(freq,size = 1, color = "random-light")
#wordcloud2(freq,size = 1, color = "random-light",shape='cardioid')
#wordcloud2(freq,size = 1, color = "random-light",shape='diamond')
```




























