---
title: "推荐信草稿"
author: " "
date: "2019/7/28"
output:
  bookdown::html_document2:
    toc: true
    theme: united
slug: refer
---

>艾瑞集团研究经理

我是中国艾瑞咨询公司上海研究二部的经理。宋骁实习期间，一直由我负责指导工作。

宋骁在实习期间展现出优秀的数据理解力。宋骁使用了因子分析(factor analysis)、主成分分析(Principal component analysis)、聚类分析(cluster analysis)等方法帮助对B级汽车用户进行细分。宋骁使用了SPSS和R语言进行数据分析，从数据的规整、清理和整合，他都亲自完成。虽然宋骁的细分方案最终并未被采用，但他的分析方法给了我们较大的启发。

宋骁参与了用户报告的撰写，其中包括制作表格和数据可视化工作(data visualization)。在用户画像和细分项目后期，需要将数据分析的结果制作成最终的报告。宋骁使用了柱状图(bar Plot)、条件分割图(Conditioning Plot)等方法完成了这部分工作。虽然这个任务存在大量的繁琐细节，但他的工作态度非常仔细。


此外，在报告撰写过程中，宋骁建议使用R Markdown等方式进行报告撰写工作。这对咨询行业是一个启示。目前咨询公司的报告主要使用PowerPoint、Word等工具撰写。统计工具的使用与报告呈现的工作是割裂开的，这隐藏着数据造假的风险。而R软件的附加产品R Markdown和knitr等工具能够实现动态可重复性报告，将数据分析和最终报告呈现完美结合。甚至通过R Shiny App工具，可以使用交互式方法(而非写代码)绘图。如果能够通过这些方法将节省报告撰写的时间，将精力用在逻辑与业务方面并提升整个行业撰写报告的效率。
这为没有R编程经验的用户带来了福音。感谢宋骁将这个工具介绍给我。   

宋骁在实习过程中取得的进步是有目共睹的。在艾瑞公司的培训中，我们讲授了大量的数据库(SQL)与大数据架构的知识。宋骁在这个过程中积累了关于数据库的知识。数据在商业的实际应用场景在在学校中很难接触到。在实际工作中。宋骁使用Navicat运行MySQL，完成了数据库查询任务。













>[卿石松](https://faculty.ecnu.edu.cn/s/2136/main.jspy)老师: ~~助教经历~~。~~课下的交流~~。~~助研经历~~。

我是社会发展学院的卿石松副教授(Associate Professor)。我非常高兴向您推荐宋骁申请你们的硕士项目。

我从大一年级就认识了宋骁，宋骁参与了我教授的《回归分析与Stata应用》(Regression Analysis Using Stata)课程。在课程期间，宋骁学习了应用于社会学研究和计量经济学的各种模型。包括线性回归、对数线性模型等。在课程的后半部分，他深入学习了高级的因果推断技术，包括工具变量法(Instrumental variables)、双重差分(difference in difference)、断点回归(Regression discontinuity design)等。与其他学生相比，宋骁在这门课的表现较为突出。

在大三年级，我担任了宋骁的学年论文(academic year paper)导师。宋骁的论文讨论了农户的土地流转行为与家庭收入的关系。他使用CFPS数据。在北京大学暑期课程的基础上，进一步发挥思路，使用面板固定效应模型和分位数回归的方法，发现土地流转行为导致的收入分配不均现象。宋骁的论文，无论在格式排版方面还是数据处理方面都体现了较强的功底。他展现出了较好的数据分析与问题意识相结合的能力。

在后续的《回归分析基础与Stata应用》课程期间，宋骁担任了我的助研职责。他负责批改同学的作业。并且在之后的时间帮我做研究，处理数据。这个项目使用CLDS数据讨论了生育意愿与生育行为之间的关系。宋骁负责了数据清洗和转换的工作，以便数据能够较好地用于统计建模。具体而言，这些工作包括处理缺失值、变量离散化、数据合并。

在这期间，宋骁和我有着较为频繁的交流。由于数据清理工作充满着大量的繁杂细节，宋骁保持了与我的沟通，确保能够出色地完成工作。

在业余时间，宋骁还学习了多种数据分析软件，包括R、Python。他还学习了机器学习算法并能够使用R或Python语言实现它们。因此，他对于数据科学和统计学有着较为全面的掌握，并且对数据分析包括商业分析方面具有相当大的热情。

>[李强](https://faculty.ecnu.edu.cn/s/2160/main.jspy)老师:关于生存分析的论文。Pre。课下与老师的交流。

我是华东师范大学社会发展学院人口研究所的李强副教授(Associate Professor)。我很荣幸向你们推荐宋骁作为你们的录取候选人。

我和宋骁的相识开始于他大二年级旁听我的研究生课程《人口统计学》(demography)。由于这门课的难度较大，《人口统计学》并未在本科生中开设。这门课程中最早介绍了R语言的使用。宋骁通过这门课的旁听，接触到了R语言。随后，他通过课下的努力不断提升自己使用R语言的数据分析技巧。

后来，宋骁选修了我为社会学本科生讲授《高级定量分析方法》(Advanced Quantitative Analysis)课程。宋骁擅长数据分析。能够使用Stata、R语言等实现数据清理、模型拟合等工作。并且，他对模型和基础统计知识也能够较好地掌握。

宋骁在课程期间，研究了吸烟与生育风险之间的关系。宋骁使用Stata软件处理了CLHLS数据。宋骁使用了人口学经典的Cox比例风险模型(Cox proportional hazard model)和离散时间风险率模型(Discrete-time Hazard Model)拟合数据。宋骁的定量论文符合学术规范且具有创新性。是一个比较优秀的人口学论文。

在课程期间，宋骁与我积极讨论定量研究中的各种问题。包括生存分析和Cox模型的技术细节。宋骁在课堂pre的时候，展现出了将社会学问题与数据分析技术结合的能力。此外，宋骁在小组讨论和展示课程中表现出了较强的领导能力。通过与同学们的积极沟通，宋骁确定了课堂展示的分工。最后通过各司其职的方式完成小组展示的工作。宋骁在广泛地阅读了应用统计与机器学习的教材与Python编程书籍。宋骁的个人网站([xsong.ltd](https://xsong.ltd))是他通过自学的成果之一。他通过学习服务器与网页知识，搭建了自己的个人网页。宋骁在学习和工作中会使用网页技术来高效完成任务。他的小组使用网页在线幻灯片进行课堂展示。













