---
title: "B级三厢车用户洞察项目"
author: "宋骁"
date: "2019-7-18"
output:
  bookdown::html_document2:
    toc: true
    theme: united
slug: rusers
---

# 数据清理
  
## 变量
  
  + 人口学：性别`S5`； 年龄`S6__1__open`；婚姻状况`D5`；孩子`D6`；教育`D3`
  + 车系`S10B`
  + 车牌`S10`
  + 生活方式、价值观`Q7__1:Q7__35`
  + 对车的态度`A0__1:A0__27`


```{r a}
library(tidyverse)
dt.car <- read.csv("C:/Users/xsong/Desktop/table/DT2.csv")
knitr::kable(table(dt.car$S5))
knitr::kable(table(dt.car$D5))
knitr::kable(table(dt.car$D3))
knitr::kable(table(dt.car$S10B))
knitr::kable(table(dt.car$S10))
#ggplot(dt.car, aes(x = S6__1__open,fill=S10B)) + geom_histogram(density = 70) +
#xlab('年龄') + 
#ylab('频数') +
#labs(fill="车型")

#ggplot(dt.car, aes(S10B,S6__1__open)) + 
#  geom_boxplot(size=0.1,outlier.colour ='sky blue',fill='sky blue') +
#xlab('车型') + 
#ylab('年龄') 
#thme(fill=guide_legend(title='车型'))
```



```{r b}
dt.car$S10B <- as.character(dt.car$S10B)
#dt.car$S3 <- as.numeric(dt.car$S3)

dta <- dt.car %>%
  select(S5,S3,S6__1__open,D5,D6,D3,S10,S10B,Q7__1:Q7__35,A0__1:A0__27,D12A) %>% #筛选列
  rename(age=S6__1__open,edu=D3) %>% #重命名      唐山 
  mutate(cityle=recode(S3,'成都'='一线','上海'='一线','广州'='一线','南京' ='二线','惠州'='二线', '郑州' ='二线','唐山'='三线', '常州'='三线', '临沂'='三线','北京'='一线城市'),
         cityregion=recode(S3,'成都'='西南','上海'='东部','广州'='南部','南京'='东部','惠州'='南部','郑州' ='中部','唐山'='北部', '常州'='东部','临沂'='北部','北京'='北部'),
    eduy=recode(edu,'初中'=9,
                     '大学本科 - 国内'=16,
                     '大学本科 - 国外'=16,
                     '大专'=15,
                     '高中'=12,
                     '技术/职业学校/中专'=12,
                     '研究生或以上 - 国内'=20),
         edu_stage = recode(edu,'初中'='初中及以下',
                     '大学本科 - 国内'='大专及以上',
                     '大学本科 - 国外'='大专及以上',
                     '大专'='大专及以上',
                     '高中'='高中或中专',
                     '技术/职业学校/中专'='高中或中专',
                     '研究生或以上 - 国内'='大专及以上'),
         age_stage = '30岁以下',
         age_stage = ifelse(age>30 & age<=40,'30-40岁',age_stage),
         age_stage = ifelse(age>40,'40岁以上',age_stage),
         child=recode(D6,'有1个孩子'='有孩子',
                      '有2个孩子'='有孩子',
                      '有3个孩子及以上'='有孩子',
                      '没有孩子'='没有孩子',
                      .default='没有结婚'),
         S10=recode(S10,'奥迪-A4L'='豪华车',
                     '宝马-320Li'='豪华车',
                     '奔驰-C180'='豪华车'),
         S10B = ifelse(S10 =='豪华车','豪华车',S10B)) %>% #重编码
  select(edu,eduy,cityle,everything()) #排序

```

# 价值观变量的主成分分析
  + 

```{r c}
pcdata <- dta %>% #用于主成分分析的数据
  select(Q7__1:Q7__35) 

#循环编码35个变量
for(i in 1:35) {
  pcdata[,i+35] <- 0
  pcdata[,i+35][pcdata[,i]=='非常同意1'] <- 1
  pcdata[,i+35][pcdata[,i]=='比较同意2'] <- 2
  pcdata[,i+35][pcdata[,i]=='谈不上同不同意3'] <- 3
  pcdata[,i+35][pcdata[,i]=='比较不同意4'] <- 4
  pcdata[,i+35][pcdata[,i]=='完全不同意5'] <- 5
}

pcdata <- pcdata %>% #保留需要主成分分析的35个变量
  select(-(Q7__1:Q7__35)) 

#主成分分析
library(psych)
fa.parallel(pcdata, fa="pc", n.iter=100,show.legend=F, main="碎石图")
pc <- principal(pcdata, nfactors=3, rotate="varimax", score=T) #方差极大旋转
pc #三个主成分为PC1,PC2, PC3

rmd <- pc$scores #2个主成分为RC1,RC2
rmd <- as.data.frame(rmd)
rmd <- rmd %>% 
  rename(lfatd1=RC1,lfatd2=RC2,lfatd3=RC3)

dta <- cbind(dta,rmd)


```

# 对车的态度主成分分析

```{r d}

pcdata2 <- dta %>% #用于主成分分析的数据
  select(A0__1:A0__27) 

#循环编码27个变量
for(i in 1:27) {
  pcdata2[,i+27] <- 0
  pcdata2[,i+27][pcdata2[,i]=='非常同意1'] <- 1
  pcdata2[,i+27][pcdata2[,i]=='比较同意2'] <- 2
  pcdata2[,i+27][pcdata2[,i]=='谈不上同意不同意3'] <- 3
  pcdata2[,i+27][pcdata2[,i]=='比较不同意4'] <- 4
  pcdata2[,i+27][pcdata2[,i]=='完全不同意5'] <- 5
}

pcdata2 <- pcdata2 %>% #保留需要主成分分析的27个变量
  select(-(A0__1:A0__27)) 

#主成分分析
library(psych)
fa.parallel(pcdata2, fa="pc", n.iter=100,show.legend=F, main="碎石图")
pc2 <- principal(pcdata2, nfactors=3, rotate="varimax", score=T) #方差极大旋转
pc2
cwb <- pc2$scores #2个主成分为RC1,RC2
cwb <- as.data.frame(cwb)
cwb <- cwb %>% 
  rename(catatd1=RC1,catatd2=RC2,catatd3=RC3)

dta <- cbind(dta,cwb)

#dta <- dta %>% 
#  select(-(edu),-(D6),-(Q7__1:Q7__35),-(A0__1:A0__27),) 

#knitr::kable(head(dta,n=10),caption = '数据概要')


```


# 聚类分析


```{r e}
cludta <- dta %>% 
  select(lfatd1,lfatd2,lfatd3,catatd1,catatd2,catatd3)

library(cluster) 
dta.scaled <- scale(cludta) #变量中心化
d <- dist(dta.scaled) #计算欧式距离
fit <- hclust(d, method="ward.D")
plot(fit, hang=-1, cex=.8, main="层次聚类图(使用Ward方法)",xlab='样本',ylab='高度')

rect.hclust(fit, k=4, border = "red")
#dta$clusters <- cutree(fit, k=4)
```

+ 相异度矩阵计算(Dissimilarity Matrix Calculation)聚类法。使用`cluster`包的`daisy`函数实现。


```{r f}
cludta <- dta %>% 
  select(eduy,lfatd2,lfatd3,catatd1)

clu <- dta %>%
  select(S10B,child,cityregion,age_stage)

cludta <- cbind(clu,cludta)

cludta$S10B <- as.factor(cludta$S10B)
cludta$age_stage <- as.factor(cludta$age_stage)

gower_dist<-daisy(cludta,metric = "gower")#分类变量的聚类
#summary(gower_dist)
h <- hclust(gower_dist)
plot(h,main = '层次聚类图(gower距离)',xlab='样本',ylab='高度')
rect.hclust(h, k=5, border = "red")

#提取最终的聚类方案
dta$clusters <- cutree(h, k=5)
knitr::kable(table(dta$clusters),caption = '每一类的样本量',align='c')

#write.table(dta, "mydata.csv")
dt.car$clusters <- cutree(h, k=5)
dt.car <- dt.car %>%
  select(rid,clusters)
write.csv(dt.car,file="C:/Users/xsong/Desktop/table/cardata.csv",row.names = F)

```


## 聚类分析后的描述性统计

```{r g}

#knitr::kable(
##dta %>%
#group_by(clusters) %>%
#summarize(平均年龄 = mean(age),
#        平均教育年限=mean(eduy)),
#digits=2,caption='分聚类类别描述性统计',align='c')

mar <- table(dta$D5,dta$clusters)
names(dimnames(mar))<-c("婚姻状况","聚类类别")
knitr::kable(mar,caption = '聚类类别和婚姻状况的交互表')
#矩阵小标题
mar <- as.data.frame(mar)
ggplot(mar,aes(聚类类别,婚姻状况)) +
  geom_tile(aes(fill=Freq),color='black') +
  scale_fill_gradient(low='white',high = 'steel blue')+
  geom_text(aes(label = Freq))+ #图中加入频数
labs(fill="频数")

knitr::kable(table(dta$S10B,dta$clusters),caption = '聚类类别和车系的交互表')
mar <- table(dta$S10B,dta$clusters)
names(dimnames(mar))<-c("车系","聚类类别")
mar <- as.data.frame(mar)
ggplot(mar,aes(聚类类别,车系)) +
  geom_tile(aes(fill=Freq),color='black') +
  scale_fill_gradient(low='white',high = 'steel blue')+
  geom_text(aes(label = Freq))+ #图中加入频数
labs(fill="频数")

knitr::kable(table(dta$S5,dta$clusters),caption = '聚类类别和性别的交互表')
mar <- table(dta$S5,dta$clusters)
names(dimnames(mar))<-c("性别","聚类类别")
mar <- as.data.frame(mar)
ggplot(mar,aes(聚类类别,性别)) +
  geom_tile(aes(fill=Freq),color='black') +
  scale_fill_gradient(low='white',high = 'steel blue')+
  geom_text(aes(label = Freq))+ #图中加入频数
labs(fill="频数")

knitr::kable(table(dta$edu_stage,dta$clusters),caption = '聚类类别和教育水平的交互表')
mar <- table(dta$edu_stage,dta$clusters)
names(dimnames(mar))<-c("教育水平","聚类类别")
mar <- as.data.frame(mar)
ggplot(mar,aes(聚类类别,教育水平)) +
  geom_tile(aes(fill=Freq),color='black') +
  scale_fill_gradient(low='white',high = 'steel blue')+
  geom_text(aes(label = Freq))+ #图中加入频数
labs(fill="频数")

knitr::kable(table(dta$age_stage,dta$clusters),caption = '聚类类别和年龄段的交互表')
mar <- table(dta$age_stage,dta$clusters)
names(dimnames(mar))<-c("年龄段","聚类类别")
mar <- as.data.frame(mar)
ggplot(mar,aes(聚类类别,年龄段)) +
  geom_tile(aes(fill=Freq),color='black') +
  scale_fill_gradient(low='white',high = 'steel blue')+
  geom_text(aes(label = Freq))+ #图中加入频数
labs(fill="频数")

knitr::kable(table(dta$child,dta$clusters),caption = '聚类类别和生育情况的交互表')
mar <- table(dta$child,dta$clusters)
names(dimnames(mar))<-c("生育情况","聚类类别")
mar <- as.data.frame(mar)
ggplot(mar,aes(聚类类别,生育情况)) +
  geom_tile(aes(fill=Freq),color='black') +
  scale_fill_gradient(low='white',high = 'steel blue')+
  geom_text(aes(label = Freq))+ #图中加入频数
labs(fill="频数")

knitr::kable(table(dta$cityle,dta$clusters),caption = '聚类类别和城市类别的交互表')
mar <- table(dta$cityle,dta$clusters)
names(dimnames(mar))<-c("城市类别","聚类类别")
mar <- as.data.frame(mar)
ggplot(mar,aes(聚类类别,城市类别)) +
  geom_tile(aes(fill=Freq),color='black') +
  scale_fill_gradient(low='white',high = 'steel blue')+
  geom_text(aes(label = Freq))+ #图中加入频数
labs(fill="频数")

```

## 态度变量的描述
```{r h1}


#循环编码27个变量
#for(i in 2:28) {
#  dta2[,i+27] <- 0
#  dta2[,i+27][dta2[,i]=='非常同意1'] <- 1
#  dta2[,i+27][dta2[,i]=='比较同意2'] <- 2
#  dta2[,i+27][dta2[,i]=='谈不上同意不同意3'] <- 3
#  dta2[,i+27][dta2[,i]=='比较不同意4'] <- 4
#  dta2[,i+27][dta2[,i]=='完全不同意5'] <- 5
#}

#for(c in 29:55) {
#print(tapply(dta2[,c],INDEX = dta2$clusters,FUN=mean))
#}

#knitr::kable(
#dta2 %>%
#group_by(clusters) %>%
#summarize(mean(A0__1),mean(A0__2),mean(A0__3),mean(A0__4),mean(A0__5),mean(A0__6),mean(A0__7),mean(A0__8),mean(A0__9),mean(A0__10),mean(A0__11)),digits=2,caption='分聚类类别描述性统计',align='c')




```


```{r h}
dta$Q7__2 <- factor(dta$Q7__2,levels=c('非常同意1','比较同意2','谈不上同不同意3','比较不同意4','完全不同意5') )
knitr::kable(table(dta$Q7__2,dta$clusters),caption = '“人活一张皮”，面子对我很重要')
mar <- table(dta$Q7__2,dta$clusters)
names(dimnames(mar))<-c("人活一张皮面子对我很重要","聚类类别")
mar <- as.data.frame(mar)
ggplot(mar,aes(聚类类别,人活一张皮面子对我很重要)) +
  geom_tile(aes(fill=Freq),color='black') +
  scale_fill_gradient(low='white',high = 'steel blue')+
  geom_text(aes(label = Freq))+ #图中加入频数
labs(fill="频数")

dta$Q7__13 <- factor(dta$Q7__13,levels=c('非常同意1','比较同意2','谈不上同不同意3','比较不同意4','完全不同意5') )
mar <- table(dta$Q7__13,dta$clusters)
knitr::kable(mar,caption = '金钱是衡量成功的最佳标准')
names(dimnames(mar))<-c("金钱是衡量成功的最佳标准","聚类类别")
mar <- as.data.frame(mar)
ggplot(mar,aes(聚类类别,金钱是衡量成功的最佳标准)) +
  geom_tile(aes(fill=Freq),color='black') +
  scale_fill_gradient(low='white',high = 'steel blue')+
  geom_text(aes(label = Freq))+ #图中加入频数
labs(fill="频数")


dta$Q7__17 <- factor(dta$Q7__17,levels=c('非常同意1','比较同意2','谈不上同不同意3','比较不同意4','完全不同意5') )
mar <- table(dta$Q7__17,dta$clusters)
knitr::kable(mar,caption = '我不盲目消费买东西以实用为主')
names(dimnames(mar))<-c("我不盲目消费买东西以实用为主","聚类类别")
mar <- as.data.frame(mar)
ggplot(mar,aes(聚类类别,我不盲目消费买东西以实用为主)) +
  geom_tile(aes(fill=Freq),color='black') +
  scale_fill_gradient(low='white',high = 'steel blue')+
  geom_text(aes(label = Freq))+ #图中加入频数
labs(fill="频数")

dta$Q7__23 <- factor(dta$Q7__23,levels=c('非常同意1','比较同意2','谈不上同不同意3','比较不同意4','完全不同意5') )
mar <- table(dta$Q7__23,dta$clusters)
knitr::kable(mar,caption = '我乐于追随时尚潮流不喜欢规矩中庸')
names(dimnames(mar))<-c("我乐于追随时尚潮流不喜欢规矩中庸","聚类类别")
mar <- as.data.frame(mar)
ggplot(mar,aes(聚类类别,我乐于追随时尚潮流不喜欢规矩中庸)) +
  geom_tile(aes(fill=Freq),color='black') +
  scale_fill_gradient(low='white',high = 'steel blue')+
  geom_text(aes(label = Freq))+ #图中加入频数
labs(fill="频数")

dta$Q7__34 <- factor(dta$Q7__34,levels=c('非常同意1','比较同意2','谈不上同不同意3','比较不同意4','完全不同意5') )
mar <- table(dta$Q7__34,dta$clusters)
knitr::kable(mar,caption = '我非常关注科技的发展喜欢研究各种新奇的东西')
names(dimnames(mar))<-c("我非常关注科技的发展喜欢研究各种新奇的东西","聚类类别")
mar <- as.data.frame(mar)
ggplot(mar,aes(聚类类别,我非常关注科技的发展喜欢研究各种新奇的东西)) +
  geom_tile(aes(fill=Freq),color='black') +
  scale_fill_gradient(low='white',high = 'steel blue')+
  geom_text(aes(label = Freq))+ #图中加入频数
labs(fill="频数")


```


# 多分类决策树

```{r i}
library(rpart)
library(rpart.plot)
dta$Q7__23 <- as.numeric(dta$Q7__23)
cont <- rpart.control(minsplit=5,maxcompete=100,xval=10,maxdepth=30,cp=0.005) #设置参数
tree.fit <- rpart(clusters ~ edu_stage+S5+age_stage+ D5+S10B+child+Q7__23+D12A,data = dta,method = "class",parms = list(split="gini"),control=cont,na.action = na.omit)
#knitr::kable(tree.fit$cptable,caption = '复杂度参数表')
rpart.plot(tree.fit)

```






