---
title: "Xiao Song"
author: " "
date: " "
slug: fck
---
Chinese Resume please click [here](/chnresume/)

### CONTACT

+ Adress：No. 53, Fanghua Road, Pudong New Area, Shanghai
+ Email：<malcolm@xsong.ltd>
+ Github：<https://github.com/ECSTA7Y>
+ Website：<https://xsong.ltd>
+ Wechat Official Account：[ApocalypseNow](https://mp.weixin.qq.com/s/yyJ3l7RTImYTKDrIynwmPA)

### SOFTWARE SKILLS
+ R, LaTeX, Stata 
+ Python, SQL, SPSS 

### RELEVANT COURSES

+ Data Analysis Using R
+ Algorithm and program design (Python)
+ Regression Analysis and Stata Application
+ SPSS Application
+ Categorical Data Analysis
+ Social Simulation and [NetLogo](http://ccl.northwestern.edu/netlogo/) Application

### EDUCATION

+ East China Normal University&emsp;2016-09~Today    
School of Social Development&emsp;(Overall GPA：3.64 /4 | Top 10%)
+ Sun Yat-Sun University&emsp;Exchange Student&emsp;2018-02~2018-07


### TRAINING EXPERIENCE

+ [Gouxionghui](http://www.xiong99.com.cn/about.php)&emsp;2019-05  
Online internship&emsp;[Credit card application scoring model](https://mp.weixin.qq.com/s/bbxWicZfk5ZMl27LbI0E1Q)   
Using Python's `Pandas`, `Numpy`, and `scikit-learn` libraries for data cleansing and modeling. A credit card scoring model was built using a logistic model and a decision tree model. The model is trained by the Cross-Validation method to predict the probability that a credit card applicant will default on the bill. The result is a complete data analysis report.

+ Peking University&emsp;2018-08  
Summer workshop  
[General Designs and Sensitivity Analysis for Causal Inference](http://www.oir.pku.edu.cn/umich/jxsz1/nsqkczsjz2018.htm)&emsp;(Grade：94/100)

+ Shanghai University&emsp;2017-07  
[6th Training Workshop on Applied Social Science Research Methods](http://caser.ust.hk/?act=course_main&id=16)  
Course: Regression Analysis and Stata Application,  Categorical Data Analysis



### ACADEMIC RESEARCH

+ Welfare Effect and Social Inequality of Land Transfer: Empirical Analysis Based on CFPS&emsp;2018-2019    
National Innovation Training Program for College Students,  Independent author  
The data of [China Family Panel Survey (CFPS)](http://www.isss.pku.edu.cn/cfps/) were used for data cleaning and econometric analysis through Stata and R. Using Unconditional Quantile Regression and Fixed Effect Model estimate the welfare effect of land transfer behavior and its impact on social inequality. Using R's `ggplot2` software package to visualize geographic information. Output chart and finally form about 12,000 words of research papers. Click [here](https://raw.githubusercontent.com/ECSTA7Y/Landtransfer/master/%E5%AD%A6%E5%B9%B4%E8%AE%BA%E6%96%87.pdf) to download the passage.



### HONORS AND AWARDS 

+ 2019 [The 2nd National University Data Driven Innovation Research Competition](http://opendata.pku.edu.cn/competition-2019.xhtml;jsessionid=200f6d0adbfa75292afed361235f) Excellence award
+ 2018 [12th Social Science Forum for Undergraduates](http://www.shupl.edu.cn/2018/1125/c1168a51557/page.htm) Highest Honor
+ 2018 Second Class Academic Honors (East China Normal University)
+ 2017 Second Class Academic Honors (East China Normal University)

### WORK EXPERIENCE

+ [Anlaiye](http://www.anlaiye.com.cn/index.html) · [Xiyou Breakfast](https://www.sohu.com/a/166510488_259362)&emsp;Campus Manager&emsp;2017-09~2018-01  
Responsible for coordinating the business of breakfast campus manager in East China Normal University, including coordinating distribution, post-sale, business contacts, and recruitment of distributors. 
Achieve the target of 1000 orders per month on average. About 10 part-time breakfast distributors were recruited in East China Normal University.






### STANDARDIZED TEST

+ **[GRE](https://www.ets.org/gre)**: 321   
(*Verbal*: 154, *Quantity*: 167, *Writing*: 3.5)  

+ **[TOEFL](https://www.ets.org/toefl)**: 100   
(*Reading*: 29, *Listening*: 24, *Speaking*: 21, *Writing*: 26)[^toefl]

+ **[CET-6](http://cet.neea.edu.cn/)**[^cet] : 549
+ **[CET-4](http://cet.neea.edu.cn/)**: 614

[^toefl]: [My Best Score](https://www.ets.org/toefl/institutions/scores/)
[^cet]: [College English Test](http://www.cet.edu.cn/)
