---
title: "城市社会学复习"
subtitle: " "
author: "宋 骁"
date: "2016/12/12"
output:
  xaringan::moon_reader:
    css: [default, zh-CN.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
### 题型
```{python}
def BinarySearch(a,target):
    left = 0
    right = len(a) - 1
    while left <= right:
        mid = (left + right)//2
        midVal = a[mid]
        if midVal <target:
            left = mid + 1
        elif midVal > target:
            right = mid - 1
        else:
            return mid
    return - 1
L = [5,7,13,25,32,46,54,62,78,83,88,91,99]
BinarySearch(L,13)
install.packages("scorecard")
```

选择 16 $\times$ 3

材料分析 15 $\times$ 2

论述 22 $\times$ 1

必考：城市性和城市化

---
class: center, middle
# 第一讲


---

### 三个重要节点

+ 农业革命

+ 工业革命

+ 世界超过一半的人居于城市

---

### 中国正处于三重转型过程中

---

class: center, middle
# 第二讲：城市社会学-思想源流
---
# 旧城市社会学

## 古典社会学家

### 韦伯

1. 防御堡垒
2. 市场
3. 独立法庭和至少部分自主的法律
4. 结社的自由；
5. 至少部分政治独立
---
## 古典社会学家

+ 齐美尔关注“现代性(modernity)：从封建经济转向理性算计为基础的金钱经济

---
## 旧城市社会学：共同点

都认为城市以及城市特定的生活方式具有特殊性，值得研究。城市扩充了人类的选择，强调理性、复杂的劳动分工、城市居民独特的城市体验。对城市独特的性质的研究成为城市社会学的主要关注点。

---
# 新城市社会学：芝加哥学派

+ 芝加哥是19世纪下半叶增长最快的西方城市之一

+ 那里的贫困、人口拥挤和犯罪逐渐变得和伦敦、曼切斯特一样显著

---

+ 城市视为社会实验室，对社会关系进行严谨的定性研究


+ 帕克
  + 人类生态学：适者生存
   
  + 竞争、主导、侵入和演替概念成为伯吉斯同心圆模型的基础。
  
  + 应集中精力研究乡村社区

---

+ 伯吉斯

  + 科班出生的社会学家
  
  + 《社会学这门科学的导论》
  
  + 城市同心圆模式


---

class: center, middle
# 第三讲：城市的起源？
---

+ 简·雅各布斯(Jane Jacobs)：农业起源于城市

  + 农业生产实际是由城市消费所创造的。城市经济发明了城市需要从农村进口的商品，然后重新创造了农村，使其能够供应那些进口商品

+ 戈登·柴尔德：旧石器时代、新石器时代、城市、工业时代

---

+ 第一次城市革命：农业革命


---
+ 资本主义工业化促使西欧涌现了许多人口超过1百万的工业城市

+ 18世纪之后西欧快速城市化标志着人类历史上第一次从乡村社会转化为城市社会，为城市出现之后的第二次“城市革命”

+ 城市死亡率高于农村

+ 阶级冲突

---
class: center, middle
# 第四讲：中国古代城市
---

+ 政治功能

+ 经济功能

---
class: center, middle
# 第五讲：中国城镇化
---

+ 1949年, 中国5.42亿人口中约有11%的人居住在城镇.新中国成立之后第一个十年，这一比例增加一倍。从1960到1978年间，中国的城镇化水平在17-18%之间徘徊。

+ 一五计划：优先发展重工业

+ 经济增长：1952-1978年GDP增长了3倍，人均收入提高了80%，不过经济增速低于世界平均水平。

+ 人均寿命大幅提高

+ 受教育水平提高

---
### 短缺经济

+ 短缺经济指给定价格下，对某种物品的需求超过了供给的数量

+ 短缺扼杀了促进技术发展的重要激励措施，因而成为导致社会主义制度下，技术发展停滞的一个根本原因

+ 1980年，中国城镇化率为19.4%，只比1952年水平高6.9个百分点。


---
### 反城镇化

+ 新中国成立至改革前，中国成功地实现了快速工业化，而城镇化水平却控制在一个相当低的水平

+ 为确保实现最大工业化和最小城市消费, 中国在计划经济时代实施了一系列具体措施，这些措施也并未导致工农一体化, 而是加大了城乡之间的差别

+ 政府试图控制大城市发展，而将资源分配到内地。一方面，城市人口（向内地）再迁移。另一方面，为国防需要，在中西部省份建设新的工业城市，平衡区域发展。
---
class: center, middle
# 第六讲：中国城镇化--改革开放至今

---

+ 收入迅速增长的同时，收入不平等状况显著恶化

### 虚假城市化

+ 外来人口

+ 真实的城镇化水平滞后于行政城镇化。



---
class: center, middle
# 第七讲：城市生活方式
---

+ 生态论/决定论(ecological theory)

+ 人口组成论(compositional theory)

+ 亚文化论(subcultural

---

+ 沃斯


+ 甘斯

+ Fischer的亚文化理论：城市与非常规(unconventionality)紧密相连


---

+ 命题1：大城市较小城市更易培育出专门化的亚文化，因此更具文化多样性。

+ 命题2：大城市比小城市具有更鲜明、更强亚文化。

+ 命题3：不同亚文化群体间的交流相互影响。

+ 命题4：城市越大，非常规（行为/观念）发生可能越大。

---

+ 不同的指数比例关系背后有两种截然不同、甚至是互相竞争的动力：一是物质上的规模经济，例如城市基础设施；二是社会互动，有利于创新和财富创造。

---
class: center, middle
# 第八讲：社区问题
---

### 社区

+ 

---

+ 互联网的使用促使社区参与的提高

+ 即使在大城市，人们仍然倾向于形成一个关系紧密的小圈子
---
class: center, middle
# 第九讲 21世纪的芝加哥学派：邻里效应

---



+ 论述社区依旧很重要，你所居住的地方，决定性地影响了你的生活

+ 你是你所住


---

+ 邻里：一个更大的社区或区域（如城市）的地理部分，通常包含居民和机构，具有鲜明的社会特征


+ 查尔斯·布斯(1885-1903)与伦敦贫困地图
   + “伦敦有多少人生活在贫困中？”
   
+ 经济结构的调整不仅导致贫困率的飙升，并且导致贫困人口的空间集聚。

+ 地理学第一定律：任何事物都与其他事物相联系，但邻近的事物比较远事物的联系更为紧密
  
---

+ 空间不平等构成了日常生活的基本维度，邻里和社区仍是差异的表现形式。


---
class: center, middle
# 第十讲 城市政治经济学
# 列斐伏尔
---

+ 马克思认为城市与农村之间的贸易更有利于城市居民

+ 列斐伏尔：社会已经被全面城市化了

+ 影响当代社会的转型，即从工业化与增长主导的时期，向城市问题主导、使寻找解决城市社会独特解决办法与手段极为紧迫的时期转型。


---



### 空间是社会组织的一部分

### 政府在管理空间中的作用

+ 抽象空间(abstract space)和社会空间(social space)的矛盾，与阶级矛盾类似，也是社会的基本矛盾。
### 资本的二级循环

列斐伏尔把资本循环分为初级资本循环(primary circuit of capital)和次级资本循环(second circuit of capital)。前者指投入工业制造的资本；后者指投入房地产业的资本。逐利的房地产业决定了城市不同区域是稳定发展、还是衰落抑或是复兴。
---

列斐伏尔把资本循环分为初级资本循环(primary circuit of capital)和次级资本循环(second circuit of capital)。前者指投入工业制造的资本；后者指投入房地产业的资本。逐利的房地产业决定了城市不同区域是稳定发展、还是衰落抑或是复兴。

---

class: center, middle
# 第十二讲 住房问题
---

发展中国家城市化的特点
+ 过度城市化(overurbanization)
+ 首位城市(primate city)
+ 非正式经济(informal economy)
+ 贫民窟(urban slum)

+ 过度城市化：城市化水平与工业化水平或经济发展水平不相匹配，前者远高于后者。

---

非正式经济
+ 进入门槛低
+ 小规模
+ 内部融资
+ 家庭作坊
+ 劳动密集
+ 没有登记
+ 缺乏管制的竞争市场
+ 不符合相关规章制度，但并非犯罪活动
+ 低技术含量

非正式经济为发展中国家15亿人提供了基本生命线。
---

class: center, middle
# 第十五讲 住房问题
---
+ 住房政策从福利住房分配转向市场导向

+ 中国房改至今，住房从福利品走向商品化，走向住房的资产化，再走向住房金融化（陈杰，2018）。
























































































































