---
title: "Pandas"
author: ' '
date: ' '
output:
  html_document:
    df_print: paged
slug: pandas
---
```{r}
library(reticulate)
```

```{python a,message = F,comment = NA,warning = F,echo = T,fig.align='center',out.width ='100%',fig.cap=' '}
import pandas as pd
import numpy as np
data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]} #字典
frame = pd.DataFrame(data)
frame

# 重编码
frame[frame['pop'] < 3] = 55
frame

data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]} #字典
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],index=['one', 'two', 'three', 'four', 'five', 'six'])
frame2["odd_even"] = frame2["state"].map({'Ohio':"Nevada",'Nevada':'Ohio'})
frame2

points = np.arange(-5, 5, 0.01) # 1000 equally spaced points




```

## Logistic Regression

```{python b,message = F,comment = NA,warning = F,echo = T,fig.align='center',out.width ='100%',fig.cap=' '}
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
iris = datasets.load_iris()
model = LogisticRegression()
model.fit(iris.data, iris.target)
actual = iris.target
predicted = model.predict(iris.data)
print(actual, predicted)


```

```{r d,engine='python'}
from sklearn import datasets
iris = datasets.load_iris()
iris.data
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from sklearn import datasets

iris = datasets.load_iris()
x = iris.data[:,0] #X-Axis - sepal length
y = iris.data[:,1] #Y-Axis - sepal length
species = iris.target #Species

x_min, x_max = x.min() - .5,x.max() + .5
y_min, y_max = y.min() - .5,y.max() + .5

plt.figure()
plt.title('Iris Dataset - Classification By Sepal Sizes')
plt.scatter(x,y, c=species)
plt.xlabel('Sepal length')
plt.ylabel('Sepal width')
plt.xlim(x_min, x_max)
plt.ylim(y_min, y_max)
plt.xticks(())
plt.yticks(())
plt.show()
```



```{r e,engine='python'}
import numpy as np
import matplotlib.pyplot as plt

n = 256
X = np.linspace(-np.pi,np.pi,n,endpoint=True)
Y = np.sin(2*X)

fig, ax = plt.subplots( nrows=1, ncols=1 )
ax.plot (X, Y+1, color='blue', alpha=1.00)
ax.plot (X, Y-1, color='blue', alpha=1.00)
plt.show()
#fig.savefig('foo.png', bbox_inches='tight')
import seaborn as sns
sns.set_style("whitegrid")
tips = sns.load_dataset("tips")
ax = sns.boxplot(x="day", y="total_bill", data=tips)
ax

```


```{r f,engine='python'}
import seaborn as sns
sns.set_style("whitegrid")
tips = sns.load_dataset("tips")
ax = sns.boxplot(x="day", y="total_bill", data=tips)
plt.show()
```

