---
title: '托福口语Task 4 Task 6'
subtitle: '解题技巧'
author: | 
  |
  |
  | [宋骁](https://xsong.ltd/)
  | <https://xsong.ltd/>
date: '`r Sys.Date()`'
fontsize: 10.5pt
output: 
  beamer_presentation: 
    colortheme: beaver
    fonttheme: professionalfonts
    theme: CambridgeUS
#http://deic.uab.es/~iblanes/beamer_gallery/individual/AnnArbor-default-default.html
---

# 答题步骤

1. summary the academic concept
2. The reading states that ...
3. 找出两个例证点
4. First, he mentions that ...
5. Second, the professor says that ...

# 具体阐释例子的方法

*Example* :

First, he mentions the strategy of making 
TV commercials of cellphone specifically 
for young peole. In these commercials, the cellphones are fun to use, in bright colors, and the kids using them are also having a good time with their peers. As a result, kids will believe these phones are made for them.

# 注意

+ 使用`->`连接听到的点
+ 讨论reading使用15-20秒左右


# 

Third, it might seem like the European traders were responsible because the sea cows became extinct soon after the Europeans arrived. But, actually, by the time that the Europeans arrived, the sea cow population was already quite small. We have evidence that the sea cow population was at its largest hundreds of years before the 1700s. So something was causing a serious and on-going decrease in the sea cow population long before the Europeans arrived in the Bering Island area. Whatever this something was, it should be considered the main cause of the extinction, not the European traders who were just the last to arrive.

# 

Finally, although the passage indicates that European fur traders kill sea cows, which might be a reason of the extinction. Instead , as the lecturer points out, when European fur traders arrived, sea cow population was relatively small. Furthermore, a long time before when those fur traders came to the island, sea cow poplulation became going down. As a result, the arrival of European fur traders cannot be a cause of the extinction.

# Task 6

1. 本质 :

+ Summerize the listening material in a STRUCTURED manner.


# 模板

+ In the lecture, the professor talks about...

+ He she uses two example to illustrate this...

+ First, the professor discusses ...(Details +  Examples), which is ... For example, ... However, ...

# 注意

+ 尽可能用过渡词 First Second For instance

+ 重视听力部分

+ 一般现在时和过去时都可以

+ 如果可以，使用复杂的表达。给出细节

+ 总结

# Task 6

| 中文| 英文 | 
|:------|:------| 
|使 降低 | lower reduce | 
|降低 |reduce decline drop fall|
|导致 |lead to cause result in create bring about|


# Task 6

+ 第6题前面的部分不重要。主要听例子。主要说例子。

+ 听清楚要说的主题是啥




