---
title: "TOEFL经验"
subtitle: " "
author: "Malcolm"
date: "2019/06/09"
output:
  xaringan::moon_reader:
    css: [default, zh-CN.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: center, middle
# 作文经验



---
## 作文

### [并列连词](http://www.en998.com/g/biaodian/020160408.html)

1. 如果并列的是两个句子，即并列句，则and 前经常加逗号

  + People will not buy as many cars as before,<font color=#FF0000> and </font> they can even use old cars.

  + In first place, as the world's natural environment becomes worse,<font color=#FF0000> and </font>  it is compelling and emergent to preserve our global environment.
  
  + All those kinds of transportation are healthier than cars,<font color=#FF0000> and </font> people will gradually give up driving cars.
  
---
## 作文

### 不要使用并列连词开始一个句子

+ ~~<font color=#FF0000>So</font> it should be worried that the remaining wilderness areas will not be admonished.~~

---

## 定语从句指代混淆的问题

Furthermore, the awareness of protecting the environment is increasing more and more,<font color=#FF0000> which</font> means cars will gradually be less and less used as main transportation.

最好改为：

Furthermore, the awareness of protecting the environment is increasing more and more, meaning cars will gradually be fewer.

---

### 新句子最好别用代词

+ However,<font color=#FF0000> it </font> was enlarged by others and the wood used was from the same tree of another painting of Rembrandt

改为：

+ However,<font color=#FF0000> the painting</font>  was enlarged by others and the wood used was from the same tree of another painting of Rembrandt





---

## 综合作文 | Integrate Writing

+ Reference the sources accordingly

---

## 独立作文

+ 首段：Just end your introduction with a thesis statement.

+ 结尾段：The concluding paragraph must contain a summary of the key points you
made in the body and a reiteration o f your thesis statement.

---

## 作文常用连接词

| 用      | 不用          | 
|:------:|:------:| 
| Commonly, Generally | ~~As we all know~~ , ~~As everybody knows~~| 
|several|~~lots of~~|
|attend|~~go~~|
|Hence| ~~So~~|
|Nevertheless = However| |
|Since |That is because |

---
## 一些地道的表达摘录

no longer 不再  
lead to 导致  
This is evidenced by 被···证实了



---
class: center, middle
# 听力经验
---
##听力

+ 喜新厌旧

+ 唯一、第一都不对


---







---






