---
title: '家庭是社会的同谋:《四百击》影评'
subtitle: ' '
author: '[宋骁](https://xsong.ltd)'
date: '2019-10-01'
output:
  bookdown::html_document2:
    toc: true
    theme: readable
slug: blows
---


# 

艺术世界中总有一些独特的作品，它们在一些人看来是如此地沉闷无趣、难以理解又毫无遮掩。而在另一些人看来又如此深刻，平静的外表后仿佛隐藏着点燃心中火焰的力量。这些作品总倾泻出一些人的呐喊，这或许是早该发出的，被社会所遗忘的声音。法国新浪潮导演弗朗索瓦·特吕弗的《四百击》就真诚地描写了一个十三岁少年的社会化历程，只是，他的故事要残酷得多。

# 

>也许有一头野兽，也许只是我们自己
——威廉·戈尔丁
《蝇王》[ 戈尔丁，威廉 《蝇王》龚志成译 上海译文出版社 1985]

第一幕。
镜头缓缓移动，一直望向远处的埃菲尔铁塔。铁塔的钢铁结构频频被近处的建筑物遮挡，使其面貌无法被全视，这破碎的侧影是否象征着社会的疏离呢？而从仰视埃菲尔铁塔的网状结构是否象征着后工业社会无比复杂的“义务与禁律”的“人工网”（列维·施特劳斯语）呢？  
课堂。一场考试。不安分的男孩们在传看一幅女人的海报。传到安托万那里不幸被老师发现。面壁。
孩子们的恶作剧，仅仅顺从玩的天性，并不邪恶。他们只想追求有趣，哪怕付出一些代价。但在社会规范力量看来，儿童的游戏是如此不合规范，必须在课堂上加以剔除的东西。  
这是一场考试，但男孩们依然无法无天（注意课堂里都是男生，安托万就读的学校应该是一所男校），规则属于弱者，而反规训的力量则属于正统的男性特质。安托万勇敢地表达着自己的不满，将抱怨写在墙上。孩子们的社会化过程在学校就已早早开始，影片中那个给安托万家长通风报信的正派小男孩，从来不受安托万等“坏小孩”的待见。
这些形式上的惩罚无法使规范的力量在拥有自由意志的孩子们心中合理化，只会加大他们与课堂的距离。正如《蝇王》中所描写的：“游戏规则不能束缚孩子的对游戏的想象力。一旦规则束缚了游戏的趣味性，就可以将其打破。”[ 同上书]成人们为逃避孤独需要在社会规范中寻找归宿，儿童却浸润在自由的天性中寻找无法被成人理解的慰藉。   
于是课堂也能成为游戏的场所：在讲授陈述句、条件句和虚拟语气时。每当老师背过身就是默许游戏开始的信号……
然而，安托万还是被要求写检讨。

#

>如果说谎对我们有利，我们为什么要说实话？
——路德维希·维特根斯坦
《天才之为责任——维特根斯坦传》[ 蒙克 《天才之为责任》王宇光 译 浙江大学出版社 2011]

回家。   
法国谚语说，一个淘气顽皮的孩子要挨四百下打才能消除灾难，怯除恶魔，变成健康听话的儿童。  
马克思说：“资产阶级撕下了罩在家庭关系上的温情脉脉的面纱，把这种关系变成了纯粹的金钱关系。”[ 马克思，恩格斯《马克思主义经典著作选读》人民出版社，北京，1999]主人公安托万生活在一个介于中产阶级和工人阶级之间的家庭。（从安托万住所糟糕的居住环境可以看出：他房间的门甚至被床挡住，无法完全打开。肮脏的楼道。但父母不是工人）但安托万是私生子，他父亲是继父。这个家庭是畸形的，冲突暴露得最明显。   
我们从安托万的家庭对话中看到大量关于“钱”的内容。母亲坚持要回安托万买面粉的零钱；母亲让安托万问父亲要零花钱；父亲严厉地追问安托万拿出的新钢笔的来源。在这个家里，金钱是亲情关系的一种纽带。钱要分得明明白白。这成了亲情的底线。如果钱的关系无法讲明白就无法维持这种亲情关系。这种畸形关系建立在不信任的基础上。   
再看看发生在“家庭”场景中的“语言符码”吧。“我让你拿的单子呢？”“我丢了。”“怪不得你学习那么差。”、“别忘了去倒那些垃圾，然后关灯。”“我不能忍受你撒谎！”母亲的言谈总是那么尖锐、带有指责的意味。   
让我们用冲突论社会学家巴希尔·伯恩施坦的“语言符码”论来分析这个家庭。他认为“工人阶级孩子的言语代表的是一种有限符码，它作为一种言语类型，维系着说话者自身的文化背景。”[ 安东尼吉登斯《社会学》第五版 李康 译 北京大学出版社 2009]母亲习惯于用直接、粗暴的“家庭矫正法”来纠正孩子的行为。这种“工人阶级式”的教育方式是一种强迫社会化的行为，“言语指向的是群体的规范。”[ 同上书]在这种符码环境下成长的孩子更倾向于叛逆。   

不是父亲的亲生儿子、幼时长期被寄养、母亲无故的打骂、父亲脾性暴躁、不合理的教育方式。从后面安托万的自述来看：父母亲在撒谎这件事上总是不留原谅的余地。在这种环境下，安托万“撒谎是因为妈妈不相信他说的实话”。可见很早以前，家庭不和谐的因子就已存在。
这个置身于其中都令他感到诚惶诚恐、极度不安全、缺乏温情的家，如何使安托万找到归宿感？这个家是无法生长萌芽的贫瘠之土。   
   单单一个不太和睦的家还不成为安托万逃离的理由。

#

>人们需要的只不过是独立的愿望，不管这种独立性需要付出什么代价，也不管它会导致什么后果。”
                                      ——陀思妥耶夫斯基
                                                                《地下室手记》[ 陀思妥耶夫斯基，《地下室手记》，伊信、蔚乾译，商务印书馆，1995]

   想到上课已经迟到、还要应付昨天的检讨。安托万和同伴逃了一次学。他们在游乐场所肆意玩乐，释放着被压抑太多的儿童天性。安托万反而在陌生人参与的转筒游戏中找到了其乐融融的酷似家的氛围。   
安托万却在回学校的路上偶遇母亲并目睹她对婚姻的不忠。接吻。   
也许安托万隐隐感觉到这是家庭破裂的征兆。也许安托万忧心忡忡的是他逃学行为的败露。总之，此事在他心中撕开一道裂痕。   
回到学校，安托万用“妈妈死了”的借口搪塞老师。躲过一劫。   
但谎言还是很快败露，他们逃学并伪造假条的行径被一个“好学生”告发给安托万的父母。父母亲都来到学校，找到他并当众掌掴他。他在同学面前俨然一个笑话。   
晚上，他给父母留下一封信并寄住在同学家。我们看到，饥肠辘辘的他做了第一件社会性的越轨行为：偷牛奶。家庭在某种意义上是社会越轨的缓冲器。一个和睦的家能够以一种恰当的方式使尚未发育成熟的未成年人缓慢社会化，使他以一种“体面”的方式获取社会地位（比如：获取学位、获得一份好的工作）。一旦未成年者失去家庭的保护，显然他的能力不足以使他进入社会。那么他就更有可能转变成越轨者。这就是为什么少年犯总能从不和谐的家庭中找到根源。   
然而，此事的影响并不像想象中的那么大。母亲起到了缓和的作用。 安托万没有想到：他知道母亲的秘密后反而使母亲的态度转变。对她来说，重要的不是安托万而是维持表面上的婚姻。母亲也是基于一种功利的算计来考虑的。安托万的逃学是小事。但整个家庭的破裂的损失是无法设想的。儿子在这里成了一种筹码。   
母亲的掩饰甚至使得安托万躲过了一场制造小火灾的惩罚。他们去看电影看电影。一时间家庭其乐融融。观众看到这里甚至迷惑了。这是真的吗？似乎这个家庭以往的所有隔阂都瞬间消失了。这还是那个充满猜疑、监视与被监视的家庭吗？事实上，这是一场秘密交换：我这里有你一个秘密，你那里有一个我的秘密。我们承诺保持缄默。互相掩饰。彼得·布劳说“权力的不平等性确立了交换中的相互性”。[ 彼得·布劳，《社会生活中的交换与权力》，李国武 译，商务印书馆，2008]安托万在这时的权力占了母亲的上风。母亲的态度仅仅维系在对这个秘密的知情上。
但这对安托万来说是种双重悲哀：如果他没有目睹母亲的出轨，她的母亲依然冷眼相对。但目睹母亲的出轨意味着母亲不爱继父，家庭有着破裂的可能。

#  

>你在巴黎的家成了你双手的祭坛
                                      ——保罗·策兰[ 策兰，保罗《保罗·策兰诗选》，孟明 译，华东师范大学出版社，2010]
                                      
在孤独的时候，安托万也曾想从文学中找到寄托。他从巴尔扎克的作品中获得灵感。他写了一篇很不错的作文。但一个上课捣蛋、在墙上乱写乱画、骗老师的学生早就被贴上了“坏孩子”的标签。理所当然，一篇优秀的作文不可能出自他手。   
这篇作文被老师指为“剽窃”，安托万无法忍受这个环境，他逃跑了。想踏入社会，他像于连·索黑尔那样逃离了家庭，逃离了令他窒息的小布尔乔亚空气。
离家出走。    
安托万像一个失魂落魄的流浪汉：寄宿朋友家、睡在夜晚的工厂、他抽烟的样子依然有些幼稚。   
偷窃。安托万走在进一步越轨的路上：他和朋友谋划挣钱，方式就是偷窃父亲单位的打印机。有一幕场景：抱着沉重打字机的安托万与朋友在街上跑，差点撞到路人们。面对手上的不知是希望还是厄运的沉甸甸的玩意，他们不知所措。仿佛街上任何一个路人都明白他们的打算，仿佛每一只眼都在盯着他们。销赃时，他们差点被黑市的伙计蒙骗。他打了退堂鼓。他后悔了。在交回打印机的时候，安托万被单位的保安发现了。   
我并不是说孩子们是一个阶级，反抗大人。而是，反抗大人的孩子们是这个社会“阶级斗争”的产物。也并不是说，安托万的父母收到压迫。而是，金钱至上的自由主义时代，利益异化了亲情、习俗、家庭等基于“血缘”的纽带。正是由于“不平等”，造成人们对阶级流动的渴望。但金钱限制了底层家庭。这意味着父母可能减少教育孩子的时间用于工作。这会从内部将适于孩子成长的“爱弥儿”式的家庭教化环境瓦解掉，取代之的是以往家庭没有的规训功能。规训不是人为能够改变的，它根植于整个社会权力结构。一旦改变（就像母亲通过与儿子的交易所做的那样），必然会造成家庭的爆裂。家庭是一组矛盾。“矛盾的各方面的发展，是越来越誓不两立，越来越相互损害，越来越不可调和。其结果是一方大获全胜，一方彻底失败，或者对立双方都同归于尽。”[ 黑格尔，《小逻辑》，贺麟 译，商务印书馆，1996]

#

>你可以避开这个世界的苦难，你完全有这么做的理由，这也符合你的天性，但正是这种回避是你可以避免的唯一苦难
                                     ——弗兰兹·卡夫卡
                                           《箴言》[ 卡夫卡，《卡夫卡集》，叶廷芳 选编，上海远东出版社，2003]
                                           
虽然安托万的目的是“赎罪”，他依然被抓个正着。父母亲再也没有对她温柔。是父亲像对待一个真正的罪犯那样将他扭送到警察局。然后他被关进一个铁笼，就像真正的罪犯那样，然后和成年犯一同被押上囚车。恐怕，此刻他在内心中也认同自己是个罪犯了吧。父母终于摆脱他，对母亲来说，安托万是一个使家庭不和睦的因素，对父亲来说，他是一张白吃饭的嘴。他的最终归宿是“少年罪犯观察中心”。   
我们应该比较这个场所与学校的不同。少管所更像一所监狱，对小事的惩罚是一种常态。管教少年犯的人们更像警察而不是教师。还有，正如一位狱友告诉安托万的那样，心理医生会为每个人记下档案。记下之前一切能孕育犯罪的行为。福柯说过：“从人成为坏人开始，他就被潜在地医学化。”[ 米歇尔·福柯《不正常的人》，钱翰 译，上海人民出版社，2010]“精神病学可以在不参照精神病的情况下把每个行为精神病化。”[ 同上书]发挥着“档案记录”功能的精神病学也是一个为“污名”群体贴标签化的过程。本来是关怀弱者的心理学有时也会变成科层制中的权力工具。   
最后是他的逃离，一劳永逸的逃离。   
他逃向大海。大海在这部影片里是没有限制的空前自由的象征。这个结尾与《麦田里的守望者》主人公霍尔顿想要的麦田一样，有一种脱离现实的慰藉感，既是对电影中的人，亦是对观众。   
可是显然，我们的世界是唯一一个没有乌托邦的世界。安托万并不能找到一片遁世的想法仅仅是一种可躲避的躲避。   
也许这并不是一个多么残酷的故事，它并没有流血与战争。但“社会化”对一个不谙世事的孩子来说可能是一个极其残酷的过程。孩子们只能以冷峻的眼睛看着这一切发生。他们无能为力。从这个意义上说：孩子成了社会任意雕刻的木偶。