---
title: 'Xiao Song'
author: 
slug: enresume
disable_comments: true
comments: false
comment: false
---

[Chinese version](/zh/zhresume/)  
[PDF](/xsong_en.pdf)

### CONTACT

+ Email: <xsong@stu.ecnu.edu.cn>
+ Github: <https://github.com/songxxiao>
+ Website: <https://xsong.ltd/en>
+ Kaggle: <https://www.kaggle.com/rikdifos>
+ Linkedin: [Click Here](https://www.linkedin.com/in/xiaosongmalcolm/)
+ Wechat Offcial Account : ApocalypseNow
<!--
+ Wechat Official Account：[ApocalypseNow](https://mp.weixin.qq.com/s/yyJ3l7RTImYTKDrIynwmPA)
 
### RELEVANT COURSES
+ Data Analysis Using R
+ Algorithm and program design (Python)
+ Regression Analysis and Stata Application
+ SPSS Application
+ Categorical Data Analysis
+ Social Simulation and [NetLogo](http://ccl.northwestern.edu/netlogo/) Application
-->

### EDUCATION

+ [East China Normal University](http://english.ecnu.edu.cn/)&emsp;2016-09~Today    
School of Social Development

+ [Sun Yat-Sun University](http://www.sysu.edu.cn/2012/en/about/about01/index.htm)&emsp;Exchange Student&emsp;2018-02~2018-07


### WORK EXPERIENCE

+ FancyDigital&emsp;Data Analyst&emsp;2020-09~Present


+ Zhongnan University of Economics and Law&emsp;Data Consultant&emsp;2020-02~2020-04 
   Remote internship. Use Xgboost, CatBoost, LightGBM and other algorithms to classify (multiclass) legal text data. The word frequency method is used to construct the feature matrix. I Used reverse-translation method to augment training data, and the cross-validation training model (sklearn) is used to obtain the cross-validation accuracy of 0.75. I write a program to make predictions on new data, so that the prediction results can be applied to any new data set.

+ [iResearch](http://www.iresearchchina.com/)&emsp;Data Analyst Intern&emsp;2019-07~2019-10
  + Using R and SPSS to analysis profile of cars' users. Through PCA and Cluster analysis, I catogorized survey data and found cars users' attitude difference.
  + Using MySQL database to help analyze users' data. 
  + Using Hive SQL to help access Hadoop database and clean data.
   
&nbsp; 

### SOFTWARE & PROGRAMMING SKILLS

+ SQL (MySQL/TiDB/Apache Doris/Clickhouse)
+ Python, R
+ Shell, Linux, Git, SPSS, Stata, MS Office, $\rm{\LaTeX}$

<!--
&emsp;(Overall GPA：3.64 /4 | Top 10%)

### TRAINING EXPERIENCE

+ [Gouxionghui](http://www.xiong99.com.cn/about.php)&emsp;2019-05  
Online Internship&emsp;[Credit Card Approval Analysis](https://mp.weixin.qq.com/s/bbxWicZfk5ZMl27LbI0E1Q)   
Using Python's `pandas`, `numpy`, and `scikit-learn` libraries for data wrangling and modeling. A credit card application model was built using machine learning models like Random Forest. The model is trained by the Cross-Validation method to predict the probability that a credit card applicant will default on the bill. The result is a complete data analysis [report](https://xsong.ltd/archives/pandas/scorecard_en).

+ Peking University&emsp;2018-08  
Summer Workshop  
[General Designs and Sensitivity Analysis for Causal Inference](http://www.oir.pku.edu.cn/umich/jxsz1/nsqkczsjz2018.htm)&emsp;(Grade：94/100)

+ Nanjing University&emsp;2018-01  
[Big Data, Cloud Computing and New Methods of Humanities and Social Sciences](https://mp.weixin.qq.com/s/eZ_gNl9qLWtD6BSZkVF8NA) [Winter Workshop](https://mp.weixin.qq.com/s/eZ_gNl9qLWtD6BSZkVF8NA)

+ Shanghai University&emsp;2017-07  
[6th Training Workshop on Applied Social Science Research Methods](http://caser.ust.hk/?act=course_main&id=16)  
Course: Regression Analysis and Stata Application,  Categorical Data Analysis
-->

### WORKS & PROJECTS

+ Spam Message Dectection R Shiny App&emsp;  
2019-12~2020-03   
This program uses 5567 pieces of English short message data as a training set and trains algorithms such as Logistic Regression, Naive Bayes, Decision Tree, Random Forest, and Support Vector Machine. The trained model is written as a Shiny App based on the R language. The user can enter a text message and select a classifier to get the classification result of the text. Considering the user's language habits, a Chinese-English bilingual interface switching function is specially set up.   
[url](https://xiaosong.shinyapps.io/spam_text/)&emsp;[github](https://github.com/songxxiao/txtnb)


<!--
### ACADEMIC RESEARCH

+ Machine Learning in Social Sciences: Based on China Education Panel Survey&emsp;2020   
Bachelor Degree Thesis ([PDF](/mlinss.pdf))  

+ Welfare Effect and Social Inequality of Land Transfer: Empirical Analysis Based on CFPS&emsp;2018-2019    
National Innovation Training Program for College Students,  Independent author  
The data of [China Family Panel Survey (CFPS)](http://www.isss.pku.edu.cn/cfps/) were used for data cleaning and econometric analysis through Stata and R. Using Unconditional Quantile Regression and Fixed Effect Model estimate the welfare effect of land transfer behavior and its impact on social inequality. Using R's `ggplot2` software package to visualize geographic information. Output chart and finally form about 12,000 words of research papers. ([PDF](http://www.baige.me/v?i=Rwy))

### HONORS AND AWARDS 

+ 2020&emsp;Kaggle  [**M5 Forecasting - Accuracy**](https://www.kaggle.com/c/m5-forecasting-accuracy)  
Estimate the unit sales of Walmart retail goods   
103rd/5558 Top2%&emsp;Silver Medal

+ 2020&emsp;Kaggle [**M5 Forecasting - Uncertainty**](https://www.kaggle.com/c/m5-forecasting-uncertainty)  
Estimate the uncertainty distribution of Walmart unit sales  
18th/909 Top2%&emsp;Silver Medal


+ 2019&emsp;Third Class Academic Honors (East China Normal University)  
+ 2019&emsp;**Daxia Cup** Student Academic Works Competition in ECNU &emsp;Third Award 

+ 2019&emsp;[The 2nd National University Data Driven Innovation Research Competition](http://opendata.pku.edu.cn/competition-2019.xhtml;jsessionid=200f6d0adbfa75292afed361235f)&emsp;Excellence award
+ 2018&emsp;[12th Social Science Forum for Undergraduates](http://www.shupl.edu.cn/2018/1125/c1168a51557/page.htm)&emsp;Highest Award

+ 2018&emsp;**Daxia Cup** Student Academic Works Competition in ECNU &emsp;Second Award 

+ 2018&emsp;Second Class Academic Honors (East China Normal University)
+ 2017&emsp;Second Class Academic Honors (East China Normal University)
+ 2017&emsp;The 12th **Wisdom Cup** Philosophical Essay Competition in ECNU&emsp;First Award

### CONFERENCE PRESENTATIONS

+ 2020-5&emsp;Machine Learning in Social Sciences, Dissertation Defense of Bachelor Degree, East China Normal University

+ 2018-7&emsp;Chinese Sociological Association Annual Meeting [Large Academic Survey Reflection and Social Quality Research Forum](http://css.cssn.cn/xsdt/zwdt/201805/t20180531_4323061.shtml) Nanjing University    
Forum hosts：Wei Li

+ 2017-11&emsp;Chinese Sociological Association   
[Winter Meeting of Social Stratification and Mobility Committee](http://sociology.nju.edu.cn/so_en/e9/79/c18475a321913/page.htm)  
[Xi’an Jiaotong University](http://en.xjtu.edu.cn/)    
Forum hosts：[Yu Xiao Wu](https://sociology.nju.edu.cn/99/2b/c17737a301355/page.htm)、[Yu Li](http://www.ssdpp.fudan.edu.cn/portal/f02f3f0f152247628e5e173df9bcecfd/orotsd.html)
-->


<!---
+ [Anlaiye](http://www.anlaiye.com.cn/index.html) · [Xiyou Breakfast](https://www.sohu.com/a/166510488_259362)&emsp;Campus Manager&emsp;2017-09~2018-01  
Responsible for coordinating the business of breakfast campus manager in East China Normal University, including coordinating distribution, post-sale, business contacts, and recruitment of distributors. 
Achieve the target of 1000 orders per month on average. About 10 part-time breakfast distributors were recruited in East China Normal University.
--->

### STANDARDIZED TEST

+ **[GRE](https://www.ets.org/gre)**&emsp;

<center>  
 <table style="border-collapse:collapse;border-spacing:0;table-layout: fixed; width: 219px" class="tg"><colgroup><col style="width: 73px"><col style="width: 73px"><col style="width: 73px"></colgroup><tr><th style="font-family:Georgia, serif !important;;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:inherit;text-align:center;vertical-align:middle">Verbal</th><th style="font-family:Georgia, serif !important;;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:inherit;text-align:center;vertical-align:middle">Quantity</th><th style="font-family:Georgia, serif !important;;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:inherit;text-align:center;vertical-align:middle">Writing</th></tr><tr><td style="font-family:Georgia, serif !important;;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:inherit;text-align:center;vertical-align:middle">154</td><td style="font-family:Georgia, serif !important;;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:inherit;text-align:center;vertical-align:middle">167</td><td style="font-family:Georgia, serif !important;;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:inherit;text-align:center;vertical-align:middle">3.5</td></tr></table>
</center>

+ **[TOEFL](https://www.ets.org/toefl)**[^toefl]&emsp;103  


<center>  
<table style="border-collapse:collapse;border-spacing:0;table-layout: fixed; width: 292px" class="tg"><colgroup><col style="width: 73px"><col style="width: 73px"><col style="width: 73px"><col style="width: 73px"></colgroup><tr><th style="font-family:Georgia, serif !important;;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;text-align:center;vertical-align:middle">Reading</th><th style="font-family:Georgia, serif !important;;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;text-align:center;vertical-align:middle">Listening</th><th style="font-family:Georgia, serif !important;;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;text-align:center;vertical-align:middle">Speaking</th><th style="font-family:Georgia, serif !important;;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;text-align:center;vertical-align:top">Writing</th></tr><tr><td style="font-family:Georgia, serif !important;;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;text-align:center;vertical-align:middle">29</td><td style="font-family:Georgia, serif !important;;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;text-align:center;vertical-align:middle">27</td><td style="font-family:Georgia, serif !important;;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;text-align:center;vertical-align:middle">21</td><td style="font-family:Georgia, serif !important;;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;text-align:center;vertical-align:top">26</td></tr></table>   

</center>

+ **[CET-6](http://cet.neea.edu.cn/)**[^cet]&emsp;549
+ **[CET-4](http://cet.neea.edu.cn/)**&emsp;614



[^cet]: [College English Test](http://www.cet.edu.cn/)

### OTHER EXPERIENCE

+ 2018-2019 East China Normal University   
Regression Analysis and Stata Application&emsp;([Shisong Qing](https://faculty.ecnu.edu.cn/s/2136/main.jspy))  
Teaching Assistant




