---
title: "宋 骁"
author: " "
date: 2019-05-10 
categories: ["R"]
slug: chnresume
tags: ["R Markdown"]
---

英文简历请点击[这里](https://hsiaosong.netlify.com/englishresume/)

### 联系方式

+ 地址：上海市东川路500号华东师范大学法商北楼201室
+ 邮箱：<xsong@stu.ecnu.edu.cn>
+ Github：[https://github.com/ECSTA7Y](https://github.com/ECSTA7Y)
+ 个人主页：[https://hsiaosong.netlify.com/](https://hsiaosong.netlify.com/)
+ 微信公众号：[ApocalypseNow](https://mp.weixin.qq.com/s/yyJ3l7RTImYTKDrIynwmPA)

### 软件技能
+ R  LaTeX  Stata(熟练)
+ Python  SQL  SPSS(入门)

### 相关课程

+ 回归分析与Stata 应用、SPSS 应用、类别数据分析、概率与统计导论
+ R数据分析、算法与程序设计基础(Python)


### 教育背景

+ 华东师范大学 上海 社会学学士（GPA：3.64/4 | 前10%） 2016/09-至今
+ 中山大学  广州 学期交换 2018/02-2018/07
+ 北京大学-密歇根大学学院 暑期课程 北京
[因果推论方法的研究设计和敏感性分析](http://www.oir.pku.edu.cn/umich/jxsz1/nsqkczsjz2018.htm)（总成绩：94/100） 2018/08


### 科研经历

+ 土地流转的福利效应与社会不平等——来自CFPS的经验证据  

国家大学生创新训练项目 独立作者 2018-2019  

使用[中国家庭追踪调查(CFPS)](http://www.isss.pku.edu.cn/cfps/)数据，通过Stata和R进行数据清理和计量经济分析。使用无条件分位数回归和固定效应模型估计土地流转行为的福利效应和对社会不平等的影响。使用ggplot2软件包进行地理信息可视化。输出图表并最终形成约12000 字的研究论文。点击[这里](https://raw.githubusercontent.com/ECSTA7Y/Landtransfer/master/%E5%AD%A6%E5%B9%B4%E8%AE%BA%E6%96%87.pdf)下载全文。

### 所获奖项 

+ 2019 [第二届全国高校数据驱动创新研究大赛](http://opendata.pku.edu.cn/competition-2019.xhtml;jsessionid=200f6d0adbfa75292afed361235f) 优秀奖
+ 2018 [第十二届本科生社会科学论坛](http://www.shupl.edu.cn/2018/1125/c1168a51557/page.htm)，特等奖
+ 2018 华东师范大学优秀学生二等奖学金
+ 2017 华东师范大学优秀学生二等奖学金

### 实践经历

+ [俺来也](http://www.anlaiye.com.cn/index.html) · [西游早餐](https://www.sohu.com/a/166510488_259362) 校园经理 2017/09-2018/01

负责统筹华东师范大学区域西游早餐校园经理业务, 包括统筹配送，售后处理，商户联络，兼职配送员招募。完成平均每月1000 订单的目标。在华东师范大学内招募约10 位校园兼职早餐配送员。

+ 狗熊会 在线实习项目 [信用卡申请评分模型](https://mp.weixin.qq.com/s/bbxWicZfk5ZMl27LbI0E1Q) 2019/05

使用Python的Pandas、Numpy和scikit-learn库进行数据清理、建模。使用Logistic模型和决策树模型建立信用卡评分模型。并且通过交叉验证(Cross-Validation)的方法预测信用卡申请者拖欠账单的概率。最终形成完整的数据分析报告。

### 标化成绩

+ GRE: 321 (Verbal:154,Quantity,167,Writing:3.5)
+ TOEFL: 92 (Reading:23, Listening:23, Speaking:20, Writing:26)
+ CET-6:549
+ CET-4: 614



























