---
title: '宋 骁 简 历'
author: ' '
slug: zhresume
disable_comments: true
comments: false
comment: false
---

[English Version](/en/enresume/)  
[PDF](/chnxsong.pdf)

### 联系方式

+ 邮箱：<malcolm@xsong.ltd>
+ Github：<https://github.com/songxxiao>
+ 个人主页：<https://xsong.ltd>
+ Kaggle：<https://www.kaggle.com/rikdifos>
+ Linkedin: [点击这里](<https://www.linkedin.com/in/xiaosongmalcolm/?locale=zh_CN>)

<!--
+ 微信公众号：[ApocalypseNow](https://mp.weixin.qq.com/s/yyJ3l7RTImYTKDrIynwmPA)
-->

### 软件技能

<!--
+ Python, SQL, SPSS &emsp;(了解)
-->
+ Python, R, SQL (包括但不限于MySQL、SQL Sever、SQLite)
+ SPSS, Stata, MS Office, LaTeX, Git

<!--
### 相关课程

+ R语言数据分析
+ 算法与程序设计基础 (Python)
+ 回归分析与Stata应用
+ SPSS应用
+ 类别数据分析
+ 概率与统计导论
+ 社会模拟与[NetLogo](http://ccl.northwestern.edu/netlogo/)应用
-->

### 教育背景

+ [华东师范大学](https://www.ecnu.edu.cn/)   社会发展学院 &emsp;2016年09月-至今
+ [中山大学](http://www.sysu.edu.cn/2012/cn/index.htm)  学期交换 &emsp;2018年2月-2018年7月

### 培训经历

+ [狗熊会](http://www.xiong99.com.cn/about.php) 在线实习项目 &emsp;2019年5月&emsp;      
课程：[信用卡申请评分模型](https://mp.weixin.qq.com/s/bbxWicZfk5ZMl27LbI0E1Q)  
使用Python的`pandas`库进行数据清理、探索性数据分析和可视化。使用IV和WOE方法分析各个特征对于因变量的预测能力。使用Logistic回归、CART决策树、随机森林、KNN、GBDT、Xgboost等方法建立信用卡评分模型。使用`sklearn`库的交叉验证(Cross-Validation)的方法训练模型并调参，预测信用卡申请者拖欠账单的概率。最终形成完整的[数据分析报告](https://xsong.ltd/archives/pandas/scorecard)。

+ 北京大学-密歇根大学学院 暑期课程 &emsp;2018年8月  
课程：[因果推论方法的研究设计和敏感性分析](http://www.oir.pku.edu.cn/umich/jxsz1/nsqkczsjz2018.htm) (总成绩：94/100)

+ 上海大学  [第6届·应用社会科学研究方法研修班](http://caser.ust.hk/?act=course_main&id=16) &emsp;2017年7月  
课程：Stata与应用回归分析基础，类别数据分析

### 项目

+ 垃圾信息判别网页应用  
2020年    
本程序使用5567条英文短信数据作为训练集，训练了Logistic回归、朴素贝叶斯、决策树、随机森林、支持向量机等算法。训练好的模型被编写成基于R 语言的Shiny App。用户输入一段短信内容文本，并选择一个分类器，就能得到该文本的分类结果。考虑到用户的语言习惯，特别设置了中英双语界面的切换功能。
[地址](https://xiaosong.shinyapps.io/spam_text/)
[源代码](https://github.com/songxxiao/txtnb)

### 科研经历

+ **土地流转的福利效应与社会不平等:基于中国家庭追踪调查面板数据的分析**&emsp;2018年-2019年   
国家大学生创新训练项目&emsp;独立作者  
使用[中国家庭追踪调查(CFPS)](http://www.isss.pku.edu.cn/cfps/)数据，通过Stata和R进行数据清理和计量经济分析。使用无条件分位数回归和固定效应模型估计土地流转行为的福利效应和对社会不平等的影响。使用`ggplot2`软件包进行地理信息可视化。输出图表并最终形成约12000 字的研究论文。([PDF](/land.pdf))  
导师：[卿石松](https://faculty.ecnu.edu.cn/s/2136/main.jspy)

### 获奖情况 


+ 2019年 华东师范大学优秀学生三等奖学金
+ 2019年 华东师范大学第二十七届 **大夏杯** 大学生课外学术科技作品竞赛&emsp;三等奖  
+ 2019年 [第二届全国高校数据驱动创新研究大赛](http://opendata.pku.edu.cn/competition-2019.xhtml;jsessionid=200f6d0adbfa75292afed361235f)&emsp;优秀奖
+ 2018年 上海市 [第十二届本科生社会科学论坛](http://www.shupl.edu.cn/2018/1125/c1168a51557/page.htm)&emsp;特等奖
+ 2018年 华东师范大学第二十六届 **大夏杯** 大学生课外学术科技作品竞赛&emsp;二等奖  
+ 2018年 华东师范大学优秀学生二等奖学金
+ 2017年 华东师范大学优秀学生二等奖学金
+ 2017年 华东师范大学 智慧杯 [哲学写作](https://xsong.ltd/archives/causal/causal)比赛&emsp;一等奖

### 会议报告

+ 2017年11月 中国社会学会 [社会分层与流动冬季论坛](http://sociology.cssn.cn/xstt/xhzywyh/201712/t20171220_3786193.shtml) 西安交通大学  
口头报告  
论坛主持人：[吴愈晓](https://sociology.nju.edu.cn/99/2b/c17737a301355/page.htm)、[李煜](http://www.ssdpp.fudan.edu.cn/portal/f02f3f0f152247628e5e173df9bcecfd/orotsd.html)

+ 2018年7月 中国社会学年会 [大型学术调查反思与社会质量研究 论坛](http://css.cssn.cn/xsdt/zwdt/201805/t20180531_4323061.shtml) 南京大学    
论坛主持人：李炜

### 实习经历

+ 中南财经政法大学&emsp;数据分析顾问&emsp;2020年2月-3月 
   远程实习。使用Xgboost，RandomForest，LightGBM等算法对法律文本数据进行分类(multiclass)。使用词频法构建特征矩阵，并利用交叉验证训练模型(Sklearn)，最终得到0.75的交叉验证准确率。最后，编写Api封装训练好的算法。对新数据进行预测，使得预测结果能够运用到任何一个新数据中。


+ [艾瑞咨询](https://www.iresearch.com.cn/)&emsp;数据分析&emsp;2019年7月-9月 
   + 使用R、SPSS软件对汽车用户进行用户画像分析工作。使用主成分分析、聚类分析法对线下数据进行无监督学习，研究不同车系用户态度区分。对汽车生产商决策提供重要参考意见，最终使用Python将结果进行数据可视化描述。
   + 使用MySQL、DBeaver数据库协助查询客户线上数据。   

&nbsp;   

<!---
+ [俺来也](http://www.anlaiye.com.cn/index.html) · [西游早餐](https://www.sohu.com/a/166510488_259362)&emsp;校园经理&emsp;2017年9月-2018年1月  
负责统筹华东师范大学区域西游早餐校园经理业务, 包括统筹配送，售后处理，商户联络，兼职配送员招募。在华东师范大学内招募约10 位校园兼职早餐配送员。完成每位配送员平均每月1000 订单的目标。
--->

### 标准化成绩

+ 学术

  + **[GRE](https://www.ets.org/gre)** 
  
<center>  
 <table style="border-collapse:collapse;border-spacing:0;table-layout: fixed; width: 219px" class="tg"><colgroup><col style="width: 73px"><col style="width: 73px"><col style="width: 73px"></colgroup><tr><th style="font-family:Georgia, serif !important;;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:inherit;text-align:center;vertical-align:middle">Verbal</th><th style="font-family:Georgia, serif !important;;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:inherit;text-align:center;vertical-align:middle">Quantity</th><th style="font-family:Georgia, serif !important;;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:inherit;text-align:center;vertical-align:middle">Writing</th></tr><tr><td style="font-family:Georgia, serif !important;;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:inherit;text-align:center;vertical-align:middle">154</td><td style="font-family:Georgia, serif !important;;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:inherit;text-align:center;vertical-align:middle">167</td><td style="font-family:Georgia, serif !important;;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:inherit;text-align:center;vertical-align:middle">3.5</td></tr></table>
</center>  

+ 英语

  + **[托福](https://www.ets.org/toefl)**[^toefl]&emsp;103  
  
<center>  
<table style="border-collapse:collapse;border-spacing:0;table-layout: fixed; width: 292px" class="tg"><colgroup><col style="width: 73px"><col style="width: 73px"><col style="width: 73px"><col style="width: 73px"></colgroup><tr><th style="font-family:Georgia, serif !important;;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;text-align:center;vertical-align:middle">Reading</th><th style="font-family:Georgia, serif !important;;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;text-align:center;vertical-align:middle">Listening</th><th style="font-family:Georgia, serif !important;;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;text-align:center;vertical-align:middle">Speaking</th><th style="font-family:Georgia, serif !important;;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;text-align:center;vertical-align:top">Writing</th></tr><tr><td style="font-family:Georgia, serif !important;;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;text-align:center;vertical-align:middle">29</td><td style="font-family:Georgia, serif !important;;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;text-align:center;vertical-align:middle">27</td><td style="font-family:Georgia, serif !important;;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;text-align:center;vertical-align:middle">21</td><td style="font-family:Georgia, serif !important;;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;text-align:center;vertical-align:top">26</td></tr></table>   

</center>

  + **[大学6级](http://cet.neea.edu.cn/)**&emsp;549
  + **[大学4级](http://cet.neea.edu.cn/)**&emsp;614  

[^toefl]: [My Best Score成绩](https://www.ets.org/toefl/institutions/scores/)



### 其他经历

+ 2019 华东师范大学 助教 
回归分析与Stata应用(教师：[卿石松](https://faculty.ecnu.edu.cn/s/2136/main.jspy)副教授)





