---
title: "ggplot2练习" 
author: ' '
date: ' '
output:
  bookdown::html_document2:
    toc: true
    theme: united
slug: ggplot
---

本文链接：

<https://xsong.ltd/archives/ggplot/ggplot2prac>

# ggplot2练习

## 学习资源(resource)

[如何使用ggplot2?](https://mp.weixin.qq.com/s/mlfCRrd0CMzoYpuCSqsVtQ)

[用局部加权回归散点平滑法观察二维变量之间的关系](https://cosx.org/2008/11/lowess-to-explore-bivariate-correlation-by-yihui)

## 二维密度图(density plot)

```{r a ,message = F, comment = NA,warning = F,cache = T, include = T,fig.align='center',out.width ='100%',fig.asp=0.6}
library(ggplot2)
data(diamonds)
knitr::kable(head(diamonds),caption="数据概要",align='c')
#原始变量关系
ggplot(diamonds, aes(carat,price)) +
geom_bin2d() +
facet_wrap(~cut, nrow = 2)
#y变量取对数
ggplot(diamonds, aes(log(carat),price)) +
geom_point() +
facet_wrap(~cut, nrow = 2)
#x变量取对数
ggplot(diamonds, aes(carat,log(price))) +
geom_bin2d() +
facet_wrap(~cut, nrow = 2)
#都取对数，最终成为线性关系。
ggplot(diamonds, aes(log(carat), log10(price))) +
geom_bin2d(bins = 100) +
facet_wrap(~cut, nrow = 2)
```

## 抽样散点图(sampled scatter)

```{r b ,message = F, comment = NA,warning = F,cache = T,include = T,fig.align='center',out.width ='80%',fig.asp=0.7}
library(haven)
setwd("E:/R_codes/capplot")
X2010 <- read_dta("2010.dta")
xy <- read_dta("id.dta")
hho <- read_dta("aggregrate.dta")
nrow(hho)

set.seed(13)#设置随机数种子
sample <- sample(1:nrow(hho),600,replace = F)#抽取600个样本
hhosampled <- hho[sample,]#抽取
nrow(hhosampled)

library(ggplot2)
scattered <- ggplot(hho,aes(x=agem,y=inc,group=type,shape=type,color=type,weight=fswt_nat)) +
  ylim(0, 20000) +
  labs(title = " ",x = "年龄",y = "人民币(元）")+
  geom_smooth(span = 10,size=1.5) + 
  geom_point(data = hhosampled, alpha = 4/7,size = 2.5 )  +
  annotate("text", x = 70, y = 200, label="数据来源：CFPS,正常散点", size = 4) + #注解
  theme(legend.position = c(0.9,0.9))#图例位置
scattered
```

```{r c,message = F, comment = NA,warning = F, include = T,cache = T,fig.align='center',out.width ='80%',fig.asp=0.6}



i <- ggplot(economics, aes(date, unemploy))
i + geom_area()

i + geom_line()

```

## 分面(facet)

```{r d,message = F, comment = NA,warning = F, include = T,cache = T,fig.align='center',out.width ='80%',fig.asp=0.8}
set.seed(711)
x = seq(0, 4, length = 100)
y = -x + jitter(rep(1:5, each = 20), 2)
z = rep(1:5, each = 20)
z <- as.factor(z)
moto <- data.frame(x,y,z)
lm1 <- lm(y ~ z,moto)
moto <- within(moto,res <- residuals(lm1))
moto1 <- subset(moto,z==1)
moto2 <- subset(moto,z==2)
moto3 <- subset(moto,z==3)
moto4 <- subset(moto,z==4)
moto5 <- subset(moto,z==5)

ggplot(moto, aes(x, y)) +
  geom_point(aes(color = z),size=3) +
  geom_smooth(method='lm',se=F)
```

```{r e,message = F, comment = NA,warning = F, include = T,cache = T,fig.align='center',out.width ='80%',fig.asp=0.6}
ggplot(moto, aes(x, y)) +
  geom_point(aes(color = z)) +
  facet_wrap(~z, nrow = 2) +
  geom_smooth(method='lm',se=F)
```

```{r f,message = F, comment = NA,warning = F, include = T,cache = T,fig.align='center',out.width ='80%',fig.asp=0.8}
ggplot(moto, aes(x,y),group=z)+
  geom_point(aes(color = z),size=3) +
  geom_smooth(data = moto1,method='lm',se=F)+
  geom_smooth(data = moto2,method='lm',se=F)+
  geom_smooth(data = moto3,method='lm',se=F)+
  geom_smooth(data = moto4,method='lm',se=F)+
  geom_smooth(data = moto5,method='lm',se=F)


```

## 地图绘制(china maps)

+ 不会分面(`facet_wrap`)者的笨办法，使用`ggplot2.multiplot`手动合并图形

```{r g,message = F, comment = NA,warning = F, include = F,cache = T,fig.align='center',out.width ='100%'} 
rm(list=ls())
library(haven)
china_map_data <- read_dta("E:/R_codes/maps/nomissing/chnprovcd.dta")

library(dplyr)
library(plyr)
# prepare work data, which needed to be filled in the map
library(readxl)
mapdata <- read_excel("E:/R_codes/ggplot2map/geodata0131.xlsx")
mapdata <- as.data.frame(mapdata)
mapdata <- select(mapdata,-(NAME)) #reverse selection
china_data <- join(china_map_data, mapdata, type="full")

china_data <- select(china_data,long,lat,group,out12,in12,out14,in14,out16,in16)

out12 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= out12)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") + 
  coord_map("polyconic") +  
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 

in12 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= in12)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") +  
  coord_map("polyconic") +  
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 

out14 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= out14)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") + 
  coord_map("polyconic") + 
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 

in14 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= in14)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") +  
  coord_map("polyconic") + 
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = c(0.9,0.6),
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 

out16 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= out16)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") + 
  coord_map("polyconic") +   
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 

in16 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= in16)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") +  
  coord_map("polyconic") +     
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 
```

```{r mergemult,message = F, comment = NA,warning = F, include = T,cache = T,fig.align='center',out.width ='100%'} 
#devtools::install_local("C:/Users/xsong/Desktop/easyGgplot2-master.zip")
library(easyGgplot2)
ggplot2.multiplot(out12,in12,out14,in14,out16,in16, cols=2)
```

# 数据长宽转换(Reshape)与分面

+ 使用[`reshape2`](https://seananderson.ca/2013/10/19/reshape/)进行数据长宽转换。

+ 使用[`facet_wrap`](https://ggplot2.tidyverse.org/reference/facet_wrap.html)进行分面

[`facet_grid()`介绍](https://ggplot2.tidyverse.org/reference/facet_grid.html#examples)

```{r h,message = F, comment = NA,warning = F, include = T,cache = T,fig.align='center',out.width ='100%'} 

library(reshape2)
long<- melt(china_data, id=c("long", "lat","group"))
library(ggplot2)
ggplot(long, aes(x = long, y = lat, group = group,fill= value)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") +
  coord_map("polyconic") +  
  facet_wrap(~variable,nrow = 3) +
  xlab('经度') + 
  ylab('纬度') +
  theme(legend.title=element_blank()) #去除图例标题

```










































