---
title: "TOEFL经验"
subtitle: "笔记与总结"
author: "[Malcolm](https://xsong.ltd/)"
date: "2019/06/09"
output:
  xaringan::moon_reader:
    css: [default, GBBB.css]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

class: center, middle
# 作文经验  
<https://xsong.ltd/slides/toefl/toefl#1>



---
## 作文

### [并列连词](http://www.en998.com/g/biaodian/020160408.html)

1. 如果并列的是两个句子，即并列句，则and 前经常加[逗号](http://www.pinlue.com/article/2018/09/1612/547220023914.html)

  + People will not buy as many cars as before,<font color=#FF0000> and </font> they can even use old cars.

  + In first place, as the world's natural environment becomes worse,<font color=#FF0000> and </font>  it is compelling and emergent to preserve our global environment.
  
  + All those kinds of transportation are healthier than cars,<font color=#FF0000> and </font> people will gradually give up driving cars.
  
---
## 作文

### 不要使用并列连词开始一个句子

+ ~~<font color=#FF0000>So</font> it should be worried that the remaining wilderness areas will not be admonished.~~

---

## 定语从句指代混淆的问题

Furthermore, the awareness of protecting the environment is increasing more and more,<font color=#FF0000> which</font> means cars will gradually be less and less used as main transportation.

最好改为：

Furthermore, the awareness of protecting the environment is increasing more and more, meaning cars will gradually be fewer.

---

### 新句子最好别用代词

+ However,<font color=#FF0000> it </font> was enlarged by others and the wood used was from the same tree of another painting of Rembrandt

改为：

+ However,<font color=#FF0000> the painting</font>  was enlarged by others and the wood used was from the same tree of another painting of Rembrandt





---

## 综合作文 | Integrate Writing

+ [综合作文模板教程](https://www.toeflresources.com/writing-section/integrated-writing)

+ Reference the sources accordingly

---

## 综合作文常用词

| 中文| 英文 | 
|:------|:------:| 
| 说 | claim, mention, suggest, state, posit, note, argue | 

+ The lecturer challenges the claims made by the author.

---

## 独立作文

+ [独立作文教程](https://www.toeflresources.com/writing-section/toefl-independent-writing-section)

+ 首段：Just end your introduction with a thesis statement.

+ 结尾段：The concluding paragraph must contain a summary of the key points you
made in the body and a reiteration of your thesis statement.


---

## 作文常用连接词

| 用      | 不用          | 
|:------:|:------:| 
| Commonly, Generally | ~~As we all know~~ , ~~As everybody knows~~| 
|several|~~lots of~~|
|attend|~~go~~|
|Hence| ~~So~~|
|Nevertheless = However| |
|Since |That is because |

---
## 作文常用连接词

| 连接词| 意义 | 
|:------|:------:| 
| since | 既然| 
|unless |除非|
|otherwise|否则|
|Meanwhile|与此同时|
|to some extent|在某种程度上|
|accordingly |1.相应地 2.因此, 于是|
|hence |因此| 

---
## 一些地道的表达摘录

no longer 不再  
lead to 导致  
This is evidenced by 被···证实了  
demand \ request \ ask sb for 要求  
cherish 珍惜  
safeguard 保卫、维护、捍卫  
fomulate 制定  
two-edge sword 双刃剑  
nightmares 噩梦  
double-sided 两面性的  
conversely 相反地  
qualified 称职的

下降：decline, reduce, decrease  
上升：improve, increase, enhance, raise, heighten


---
prior 先  
posterior 后  
What's more 何况


---
class: center, middle
# 口语经验
---

## 评分标准

+ 清楚

+ 有节奏

+ 简单句、复杂句结合

+ **切题**、逻辑一致。

+ 

---

1. state your point 

2. optional transition

3. point 1.

例子和论理的顺序颠倒。

+ Avoiding reapting words

use transitional words.

---
# Advantage & Disadvantages Templates :

+ **undoubtedly**

+ Meanwhile, an obvious advantage of ... is...
---
## 地道的表达

I feel this way because ...  
There's lot of advantages that  
I believe ...  
inapporiate to ...  
call off 取消  
set off 出发  
touch my heart 触动我  
turn out 结果是  
conflict 时间冲突  
throw up 呕吐  
freak 怪物  
tender gentle 温柔的  
vagina 阴道  
sober 清醒 
---
## 地道的表达

freaked out 吓坏了  
go ahead 继续说  
exactly 确实是  
we have nothing in common 我们没有共同点  
be dying to do sth 十分想做某事  
highly recommend 推荐   
durable 耐用的  
clingy 粘人的(形容女朋友)  
a big fan of 
mainstream 主流的
on trend 流行的



---
### 口语：task 4

+ 文章出来直接读！ 没时间记笔记！

+ 读文章时候记得总结the concept

+ 详细阐述例子。不要说太多理论。把精力放在听力中！

[2019托福改革删除原先task1和task5](https://www.sohu.com/a/316493115_340226)
---

### 口语：task 6

+ 简单summarize一下主题，引入两个方法。

+ 主要听例子,说例子

+ 记笔记的时候最好换个说法


---
class: center, middle
# 听力经验
---
##听力

+ 喜新厌旧

+ 唯一、第一都不对

+ 答题时候回看笔记会得到答案


---
class: center, middle
# 阅读经验
---

## 阅读

+ 开始得别太早，不然会被吵

+ 最后一题总结题注意**introductory sentence**

---













