---
title: '第十二届中国R语言大会'
author: ''
date: '2019/12/22'
slug: r_twelve
---

咳咳，先说点题外话。这个公号搁置很久了。不是因为懒，而是因为微信公众系统之烦。我写个文章需要各种排版。尤其是有代码、图片的文章，极其繁琐复杂。所以有些做好的分析就直接Post在个人网站上了。当然坏处就是阅读量少。不过我相信真正愿意重复我代码的同学是一定会访问我网站的。不然也没有读应用文章的需求。现在我更喜欢分享Notebook的一个平台是Kaggle。代码写好后，直接放在Docker云容器上跑，算力顶呱呱。

言归正传。

2019年12月21日。我来华东师范大学参加了第十二届中国R会议。R会议一年一次。北京上海广州都有。某大佬曰过：

>没有记录下来的事情就没有发生

本着这种精神，也因为信息接收过多，我决定写篇小文总结一下。

因为会议是9点开始。因此我7点多起床，吃饭然后提前到。直奔中北校区科学会堂。整个大会非常朴素，处处体现出民间论坛的“草根”性质。

首先是华东师范大学统计系汤银才教授简单介绍了华师大统计系。他的讲座讨论了统计学习与机器学习的关系。实际上，人们通常并不区分这两个术语的细微差异。但传统统计与机器学习的争论由来已久。这点在Leo Breiman 《Two Cultures》有所体现。总之，这两个领域总是在用不同的术语讨论相同的东西。如“变量”与“特征”。而Logistic模型也不过是神经元模型非常相似。只不过一个说“连接函数”，一个说激活函数等等。剩下的都是老生常谈啦。

第二位讲者是来自香港中文大学的成生辉。他分享了他所在研究院的一款BI产品。具体就是输入数据进行无代码可视化的交互界面。这个我可能用不到。

第三位比较印象深刻。是饿了么的李哲。他带来了一个有趣的工业应用案例：使用知识图谱优化餐饮产品的构建。这位大佬令我印象最深刻的是他讲清楚了知识图谱的概念。知识图谱比深度学习的模式识别更为高级的AI应用。它能够回答诸如“饿了么的公司名称叫什么？”、“阿里投资了哪些公司？”这种需要人类经验积累的问题。



下一位是

这个公司类似R Studio，是为广大的R个体用户提供服务的商业公司。





总之，听完这一系列报告，我愈发感觉到自己决定从社科转到DS是正确的选择。毕竟，社科的领域更为传统、保守，离工业界更远。同时，关于Shiny App、Docker、Spark、Linux等知识是很好的触发点。未来应该补全自己在这些方面的空白。当然重中之重是学好NLP技术。







