---
title: "ggplot2练习" 
subtitle: '描述与探索'
author: '[宋骁](https://xsong.ltd)'
date: ' '
output:
  bookdown::html_document2:
    toc: true
    theme: united
slug: ggplot
## bookdown themes:https://bookdown.org/yihui/bookdown/theming.html
---

本文链接：

<https://xsong.ltd/archives/rbasic/ggplot2prac>


# 便捷命令速查

```r
#去除图例标题
theme(legend.title=element_blank())
#去除图例
theme(legend.position='none')
```

# 笔记

+ 在`aes`函数里面的参数，如`fill`、`color`、`shape`，控制的是图形的映射对象。它将特定变量映射为统计图形的特定元素。而`+`后面的图形函数中的参数，仅仅是图形的附加属性。无法根据特定变量变化。


# 资源

[如何使用ggplot2?](https://mp.weixin.qq.com/s/mlfCRrd0CMzoYpuCSqsVtQ)

[ggplot2 in R](http://rpubs.com/faststar/442420)

[ggplot2 Shiny App](https://github.com/cardiomoon/ggplot2new)

[现代统计图形](https://bookdown.org/xiangyun/msg/)

[Python ggplot库](http://ggplot.yhathq.com/)


```{r,message = F, comment = NA,warning = F}
library(ggplot2)
library(dplyr)
library(plyr)
library(readxl)
library(modelr)
library(haven)
library(readr)
library(easyGgplot2)
library(reshape2)
library(rgdal)
`%>%` <- magrittr::`%>%`
```


# 密度可视化

```{r,message = F, comment = NA,warning = F,cache = T,fig.align='center',out.width ='100%',fig.asp=0.6}
data(diamonds)
ggplot(diamonds, aes(log(carat), log10(price))) +
geom_bin2d(bins = 50) +
facet_wrap(~cut, nrow = 2)

ggplot(diamonds, aes(log(carat), log10(price))) +
geom_hex() +
facet_wrap(~cut, nrow = 2)
```

# 抽样散点图

```{r 1,message = F, comment = NA,warning = F,cache = T,fig.align='center',out.width ='80%',fig.asp=0.7,fig.cap='`ggplot2`按图层绘图。为防止散点堆叠，图中散点经过抽样。lowess曲线是根据原始数据绘制。不同图层可使用不同数据。位于`ggplot`下方的图层将被堆叠在上方。'}
hatdt <- read_dta('E:/R_codes/capplot/aggregrate.dta')
set.seed(20191001)
sample <- sample(1:nrow(hatdt),600,replace = F)
sampled <- hatdt[sample,]

ggplot(hatdt,aes(agem,inc,shape=type,color=type,weight=fswt_nat)) +
  geom_jitter(data=sampled,height=550,width=5,size =1.2) +
  geom_smooth(span=10,size=1) + 
  ylim(0, 20000) +
  labs(x = "年龄",y = "人民币(元)") +
  annotate("text", x = 70, y = 100, label="数据来源:CFPS", size = 4) +
  theme_bw()
```

# 模型可视化

+ 例子来自：[用局部加权回归散点平滑法观察二维变量之间的关系](https://cosx.org/2008/11/lowess-to-explore-bivariate-correlation-by-yihui)。

+ 使用[`modelr`](https://r4ds.had.co.nz/model-basics.html)包进行模型拟合。

```{r 2,message = F, comment = NA,warning = F,cache = T,fig.align='center',out.width ='100%',fig.asp=0.8,fig.cap='散点图的颜色代表不同组。左上:简单OLS拟合。右上:令每个组斜率相同、截距不同(固定效应)。相当于将组别变量`z`作为控制变量。原本的正相关相关关系颠倒为负相关。左下:对每个组分别拟合线性模型。各组斜率不同，截距也不同。'}
set.seed(91)
x <- seq(0, 4, length = 100)
y <- -x + jitter(rep(1:5, each = 20), 2)
z <- rep(1:5, each = 20)
z <- as.factor(z)
dt <- data.frame(x,y,z)

modela <- ggplot(dt, aes(x, y)) +
  geom_point(aes(color = z),size=2) +
  geom_smooth(method='lm',se=F)+
  theme(legend.position='none')

moda <- lm(y ~ x + z,dt)
grid <- dt %>%
data_grid(x,z) %>%
gather_predictions(moda)
          
modelb <- ggplot() +
  geom_point(data=dt,aes(x, y,color=z,group=z),size=2) +
  geom_line(data=grid, aes(pred,x,group=z),
            size=0.75,color='blue') +
  ylim(0.3,2.1)+
  xlim(-0.1,4.1)+
  theme(legend.position='none')

modelc <- ggplot(dt, aes(x, y,group=z)) +
  geom_point(aes(color = z),size=2) +
  geom_smooth(method='lm',se=F)+
  theme(legend.position='none')
ggplot2.multiplot(modela,modelb,modelc,cols=2)

```

# 分面

+ 基于两个变量的分面:`facet_grid`

```{r,message = F, comment = NA,warning = F,cache = T,fig.align='center',out.width ='80%',fig.asp=0.6}
bara <- read_csv("F:/Mysite/Mysite/static/slides/mlepre/bar1.csv")
ggplot(bara,aes(reorder(car
,value),value,color=segment
,fill=segment
)) +
  geom_bar(stat = 'identity',width = 0.3) +
  coord_flip()+
  geom_text(aes(label = value,position='right',hjust=0.8),size=2.7,color='black') +
  facet_grid(phase~segment,space = "free_x") +
  labs(x=" ",y=" ") + 
  theme_classic() +
  theme(legend.position='none')
```

# 地图

+ 不分面(`facet_wrap`)的笨办法，使用`ggplot2.multiplot`手动合并图形。

```{r,echo=F,message = F, comment = NA,warning = F,cache = T} 
rm(list=ls())
china_map_data <- read_dta("E:/R_codes/maps/nomissing/chnprovcd.dta")

mapdata <- read_excel("E:/R_codes/ggplot2map/geodata0131.xlsx")
mapdata <- as.data.frame(mapdata)
mapdata <- select(mapdata,-(NAME)) #reverse selection
china_data <- join(china_map_data, mapdata, type="full")

china_data <- select(china_data,long,lat,group,'2011土地租出','2011土地租入','2013土地租出','2013土地租入','2015土地租出','2015土地租入')

out12 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= out12)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") + 
  coord_map("polyconic") +  
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 

in12 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= in12)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") +  
  coord_map("polyconic") +  
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 

out14 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= out14)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") + 
  coord_map("polyconic") + 
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 

in14 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= in14)) +
  geom_polygon(colour='brown',size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") +  
  coord_map("polyconic") + 
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = c(0.9,0.6),
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 

out16 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= out16)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") + 
  coord_map("polyconic") +   
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 

in16 <- ggplot(china_data, aes(x = long, y = lat, group = group,fill= in16)) +
  geom_polygon(colour="brown",size=0.2) +
  scale_fill_gradientn(colours = c("yellow", "red"),na.value = "white",
                       breaks = c(10,20,30,40),limits=c(0,43), guide = "legend") +  
  coord_map("polyconic") +     
  theme(              
    panel.grid = element_blank(),
    panel.background = element_blank(),
    axis.text = element_blank(),
    axis.ticks = element_blank(),
    axis.title = element_blank(),
    legend.position = "none",
    plot.title = element_text(hjust = 0.5,vjust=0.9, size=11),
    legend.title = element_text(size=0),
    plot.margin = unit(c(0.001,0.001,0.001,0.001), "cm")) 
```

```{r,message = F,comment = NA,warning = F,cache = T,fig.align='center',out.width ='100%'} 
ggplot2.multiplot(out12,in12,out14,in14,out16,in16, cols=2)
```

+ 使用[`reshape2`](https://seananderson.ca/2013/10/19/reshape/)进行数据长宽转换。

+ 使用[`facet_wrap`](https://ggplot2.tidyverse.org/reference/facet_wrap.html)进行分面

+ [`facet_grid()`介绍](https://ggplot2.tidyverse.org/reference/facet_grid.html#examples)

```{r,message = F, comment = NA,warning = F,cache = T,fig.align='center',out.width ='100%',fig.cap='中国土地流转的空间分布。北京、天津由于农户过少而设为缺失。CFPS未调查的省份数据缺失。土地流转发生率=当年参与土地流转的农户数/当年农户总数。数据经过加权处理，具有全国代表性。'} 
long <- melt(china_data, id=c("long", "lat","group"))

ggplot(long, aes(x = long, y = lat, group = group,fill= value)) +
  geom_polygon(colour='brown',size=0.2) +
  scale_fill_gradientn(colours = c('yellow', 'red'),na.value = 'white',breaks = c(10,20,30,40),limits=c(0,43), guide = 'legend') +
  coord_map('polyconic') +
  facet_wrap(~variable,nrow = 3) +
  labs(x='经度',y='纬度',fill = '土地流转发生率') +
  theme_bw()

```

## 气泡地图

```{r,message = F, comment = NA, warning = F,cache = T,fig.align='center',out.width ='100%'} 
bottom  <- readOGR(dsn = "E:/R_codes/maps/CHN_adm/CHN_adm2.shp",stringsAsFactors=F)

bottomdata <- fortify(bottom)         
x <- bottom@data          
xs <- data.frame(x,id=seq(0:344)-1)        

china_map <- join(bottomdata, xs, type = "full")          
fills <- read_excel("E:/R_codes/maps/pointmap/citydis.xlsx")

china_map <- join(china_map,fills, type = "full")   
point <- china_map
point <- na.omit(point)
midpos <- function(x) mean(range(x,na.rm=T)) 
centres <- ddply(china_map,.(NAME_2),colwise(midpos,.(long,lat)))
center <- join(centres,fills, type = "full") 
center  <- na.omit(center)

ggplot(china_map,aes(x=long,y=lat)) + 
  geom_polygon(aes(group = group),fill="white",color="black",size=0.1) + 
  geom_point(mapping = aes(x=long, y=lat, size = freq),data = center, colour = 'red') +
  coord_map("polyconic") +
  labs(x='经度',y='纬度') +
  theme(legend.title=element_blank()) + 
  theme_bw()

```

# 误差可视化

```{r,message = F, comment = NA, warning = F,cache = T,fig.align='center',out.width ='100%',fig.asp=0.6} 
df <- data.frame(grp = 1:17, fit = c(1,2,2,3,4,6,7,9,15,16,17,19,18,8,10,11,2), se = 2)

era <- ggplot(df,aes(grp,fit,ymin=fit-se,ymax=fit+se)) +
  geom_point()+
  geom_line()+
  geom_errorbar(width=0.3)

erb <- ggplot(df,aes(grp,fit,ymin=fit-se,ymax=fit+se)) +
  geom_line()+
  geom_linerange()
  
erc <- ggplot(df,aes(grp,fit,ymin=fit-se,ymax=fit+se)) +
  geom_line()+
  geom_pointrange(size=0.2)

ggplot2.multiplot(era,erb,erc,cols=2)

```

# 平行坐标图(Parallel Coordinate Plot)

```{r,message = F, comment = NA, warning = F,cache = T,fig.align='center',out.width ='100%',fig.asp=0.6}

data(kyphosis,package = 'rpart')
kyphosis <- kyphosis %>% 
  select(Kyphosis,Age,Start,Number,everything())

library(GGally)
ggparcoord(kyphosis, columns = 2:4, groupColumn = 1, scale = "uniminmax") + 
  geom_line(size = 1.2)

```

# 5折交叉验证

使用`modelr`包的函数

```{r,eval=F,message = F, comment = NA, warning = F,out.width ='100%',fig.asp=0.6}
data('titanic_train')
titanic_train$Pclass <- as.factor(titanic_train$Pclass)
cv1 <- crossv_kfold(titanic_train, 5)
library(purrr)
models <- map(cv1$train, ~ glm(Survived ~ Sex+Age+SibSp+Parch+Fare+Embarked,titanic_train,family=binomial(link='logit')))

errs <- map2_dbl(models, cv1$test, rmse)
r2 <- map2_dbl(models, cv1$test, rsquare)
mean(errs)
hist(r2)


```


























