---
title: "个人陈述草稿"
author: "[宋骁](https://xsong.ltd/zh/)"
date: " "
output:
  bookdown::html_document2:
    toc: true
    theme: united
slug: ps
---
+ 术语用括号标出

作为一名社会学系本科生。我在本科期间修读了若干课程，这些课程均要求提交一份经验性研究。在课程中我对于研究方法是困惑的。在以访谈为主的定性研究不能保证科学性的情况下，定量研究是否能够为社会学研究提供更科学的方法呢？带着这个疑问，我选修了卿石松老师的定量方法课。在学习了基本的概率统计和回归分析知识后。我发现统计模型的有趣之处：统计方法不但能超越相关关系，还能够把握到因果关系，预测未来的状况。比如，通过一个人的教育、家庭、婚姻等变量预测收入。此外，这些关系可以通过可视化手段展示出来。这让我爱上了数据分析！为了进一步探究统计方法在社会学中的应用。我自学了R语言和数据可视化。

在本科期间我跟随卿石松老师做了多个关于社会分层与不平等(Social stratification and inequality)方向的科研项目。一开始，我的研究着眼于性别不平等领域。我讨论了性别观念、工作时间、家务劳动时间对夫妻双方的婚姻满意度的影响。这个研究使我走入了计量经济学风格的定量研究范式中。在做这个研究的过程中，我学习了方差分析(Analysis of Variance,简称ANOVA)、线性回归(Linear Regression)、广义线性模型(Generalized linear model)等统计学方法。我在论文中注重应用统计图形(Statistical Graphics)进行交流。

第二段科研经历延续了对婚姻与社会不平等主题的研究。我讨论了外貌(apperance)作为一种“非认知能力”(non-cognitive ability)对婚姻行为的影响。我惊讶地发现美丽的外表并不能帮助人们更快地走入婚姻关系。经济和教育水平的门当户对才是决定婚姻的第一因素。这种婚姻匹配模式也促进了阶层的固化。在这个研究中，我应用生存分析(Survival Analysis)方法，将结婚事件的发生事件纳入考虑。生存分析通过分析促使不同状态的转换(生到死、未婚到已婚)的时间效应来理解社会，它拓展了我对统计方法的认识。很多结果并非由一两个单独的原因来决定，而可能随时间推移自然发生。现实世界的复杂性让我意识到之前掌握的统计知识是远远不够的。我决定更深入地学习因果推断的方法。

大三年级，我选修了因果推断框架下的计量经济学(Econometrics)课程。通过这些奇妙的方法，模型能够剥除其他混淆因素的影响，单独估计自变量对因变量的纯因果效应。比如，双重差分(difference-in-difference)模型引入了自然实验(natural experience)设计，巧妙地估计出因果效应(Causal Effect)。在学习计量(Metrics)课程的同时，它们的思想深深吸引了我。在学年论文选题的时候。我决定使用面板数据(Panel Data)的方法，考虑土地流转行为对中国农户的家庭收入的影响。同时，分位数回归(Quantile regression)的处理办法也被用于估计社会不平等问题。

为了进一步了解机器学习算法以及编程语言以及为QMSS项目做准备。我报名参加了一个在线培训项目。这个项目要求学员使用Python和银行历史数据建立[信用卡申请评分模型](https://xsong.ltd/archives/pandas/scorecard_en)。在这期间，我学习了几个较为主流的机器学习算法。如决策树(classification and regression trees)、随机森林(random forest)、AdaBoost等。我阅读了《An Introduction to Statistical Learning with Applications in R》一书。我这些模型能够很好地对个体的状况进行预测。它们能够通过大量学习器的组合掌握高维变量(High dimensional variables)的非线性关系，提取数据中潜藏的大量信息。同时，交叉验证(Cross-Validation)的方法能够客观评估模型在新数据集的表现。这使得机器学习模型拥有比传统统计学模型更为强大的预测和泛化能力。

我着迷于机器学习模型思路的精致和巧妙。我萌生了使用机器学习算法写作毕业论文的想法。目前我正在研究初中生数学成绩的预测方法。我使用XGBoost算法训练模型，通过学生个人、家长、班级、学校多方面的数据预测学生的数学成绩，并且计算出每个变量的重要性。


未来我的职业规划是成为一名计算社会科学家(Computational Social Scientist)。我将继续深入了解Python和R语言。将机器学习知识引入到社会科学领域。以往关于社会分层与不平等的研究大多使用传统的定量模型。而我想使用机器学习模型研究以往的问题。未来我想使用诸如爬虫、文本分析、自然语言处理(Natural Language Processing)的高级方法研究非结构化数据。QMSS的课程和教学设置将是我打成目标的不可或缺的一环。



<!---
未来我愿意进入互联网行业工作。在之后的职业生涯中，我希望能够进入互联网或咨询行业从事数据分析或数据科学方面的工作。我将进一步着眼于数据在业务场景中的应用。我感兴趣的是如何让数据产生真正的商业价值。而这需要对具体业务场景的深入了解。在艾瑞咨询公司的实习经历使我了解到真实的商业界如何在使用什么样的算法和模型。在这个公司中，我接触到了大数据架构。我们在工作中会大量使用爬虫(Python)和自然语言处理等方面的知识。由于我之前缺少这方面的训练，希望能够在NLP方面取得进步。



尽管计量经济学的因果推断框架对于理解变量的机制有着十分重要的用途，但这些方法对事件的预测效果并不好。一个问题深深困扰着我：为什么在因果关系被知晓后却仍然无法对世界做出很好的预测？

后来我转而自学机器学习框架下的统计模型。

我申请...学校的原因是。这个项目旨在于

。由于如今各行各业的公司都会在业务中收集大量的数据，我希望能在真实的业务场景中让数据产生价值。并且能将数据思维引入到我今后将会进入的行业中去。

在政治系做RA

暑假在新闻学系是TA

学生社团的副社长

QMSS 中间可以申CPT。在学校的话不需要。

*Computational Social Scientist* Story Line 

Research Design的重要性。 想学Experimental Design

machine learning的东西 信用卡模型

99%的同学没啥学术成果

Research Interest集中在*不平等*领域。

把之前的经历串起来 每段经历都是用来服务career goal的。

在某一节课上对这个感兴趣。稍微提一下。从*机器学习*的角度研究之前感兴趣的问题。

稍微偏后面写这个项目能给我提供的东西。

通过*术语*来体现自己的专业。可以保留一些很具体的句子。每段经历怎么引向了下一段经历。这段经历激发了什么思考。希望把这种方法。每一段的首句开门见山总结下。不要拐来拐去。对社会不平等的感悟。

日期：趁热打铁，列提纲。快的话，两到三周。

哥大Graduate School。TOEFL。

DDL是2.13。

自己的经历非常有特色。
--->












