---
title: "Untitled"
author: "Malcolm"
date: "2019/12/19"
output: html_document
---

```{r}
read = '{"rumorCode":"K1CaN8wJj76ol","title":"@隆闯天涯 举报@浅雪深洋 不实信息","informerName":"隆闯天涯","informerUrl":"http://weibo.com/u/1842734325","rumormongerName":"浅雪深洋","rumormongerUrl":"http://weibo.com/u/2592892063","rumorText":"急找孩子，求转 实验小学寻人启事13930886687帮忙扩散，今天上午一个三岁多小女孩在锦绣花园小区附近被人拐走了，小女孩能说出她爸爸的手机号码 从监控上看是被一个四十多岁男人抱走了现大人都急疯了 有知情者请告之 万分感谢 看到信息的兄弟姐妹留意一下 联系人 张静杰13930886687如果看一眼懒得 ","visitTimes":3,"result":"经查，该微博称“有孩子被抢”不实，类似消息近两年在网上广为流传且都已经被当地警方辟谣，详情：http://weibo.com/2656274875/CodNboTCH，被举报人构成“发布不实信息”，虽无即时危险，但应予澄清，现根据《微博社区管理规定》 （http://service.account.weibo.com/roles/guiding）第19条，予以标识处理。","publishTime":"2016-06-15 09:02"}
{"rumorCode":"K1CaN8wJj76ok","title":"@隆闯天涯 举报@cat精品微店 不实信息","informerName":"隆闯天涯","informerUrl":"http://weibo.com/u/1842734325","rumormongerName":"cat精品微店","rumormongerUrl":"http://weibo.com/u/5722939786","rumorText":"急帮忙转寻人启示13759695559帮忙扩散，今天上午一个三岁多小女孩在世纪家园小区附近被人拐走了，小女孩能说出她爸爸的手机号码，从监控上看是被一个四十多岁男人抱走了现大人都急疯了，有知情者请告之，万分感谢！看到信息的兄弟姐妹留意一下！·联系人，张静杰13759695559如果看一眼懒得转的冷漠的 ","visitTimes":3,"result":"经查，该微博称“有孩子被抢”不实，类似消息近两年在网上广为流传且都已经被当地警方辟谣，详情：http://weibo.com/2656274875/CodNboTCH，被举报人构成“发布不实信息”，虽无即时危险，但应予澄清，现根据《微博社区管理规定》 （http://service.account.weibo.com/roles/guiding）第19条，予以标识处理。","publishTime":"2016-06-15 09:06"}
{"rumorCode":"K1CaN8wJi7ase","title":"@浪爷爷之2046 举报@江小鱼 不实信息","informerName":"壹刻亦光年-ZMQ","informerUrl":"http://weibo.com/u/2858506305","rumormongerName":"江小鱼","rumormongerUrl":"http://weibo.com/u/1212040547","rumorText":"：#微博辟谣# 虚假消息 .            ","visitTimes":1486,"result":"被举报人发微博称：“昨悉朝阳区群众又一重大战果，史诗巨制《监狱风云》添一重磅小鲜肉，吸毒队完胜嫖娼队”。该消息一经公布，引起网友和舆论的密切关注，甚至引发对一些知名演员的无端猜测。但后经站方与@江小鱼 方面核实，@江小鱼 始终不能提供任何能够证实其消息真实性的证据，并将此前发布的微博删除。且@平安北京 也就此提示网友对于“来源不明的消息，不要轻信和传播，更不要编造谣言。”现站方根据《微博社区管理规定》第20条之规定，对构成“发布不实信息”的账号@江小鱼予以禁言、禁被关注15天，扣除信用积分10分的处罚。","publishTime":"2016-06-14 14:20"}
{"rumorCode":"K1CaN8wJg7a0f","title":"@无处安放大脸喵 举报@石梓钰 不实信息","informerName":"无处安放大脸喵","informerUrl":"http://weibo.com/u/5198423515","rumormongerName":"石梓钰","rumormongerUrl":"http://weibo.com/u/2032945394","rumorText":"        ：#上海城管把商家打死#上海城管把学弟的亲舅妈打死！发生在学弟身上的真事！希望社会还个公道！                             ","visitTimes":9,"result":"此微博称“上海市颛桥城管打死人了”不实，据@警民直通车-闵行 通报：市容管理人员葛路某准备骑电瓶车离开现场，被路边设摊人员黄某阻拦。黄某儿子葛树某驾驶一辆蓝色卡车撞向电瓶车，黄某被电瓶车带倒在地，当场头部出 血，后被送往医院经抢救无效死亡，并非城管打死人。详情：http://weibo.com/3236934434/DzDq3vS8K，被举报人言论构 成“发布不实信息”。现根据《微博社区管理规定》第19条，对被举报人处理如下：扣除信用积分2分。上述处理在公布后60分钟内生效。","publishTime":"2016-06-13 16:18"}
{"rumorCode":"K1CaN8wJg7a0e","title":"@无处安放大脸喵 举报@小小小小小吖莲 不实信息","informerName":"无处安放大脸喵","informerUrl":"http://weibo.com/u/5198423515","rumormongerName":"小小小小小吖莲","rumormongerUrl":"http://weibo.com/u/5246061392","rumorText":"        ：上海城管暴力执法，同学的舅妈被打死了，报警了可是公安只说等回复，求给一个公道，城管为什么可以这么嚣张？求解释？ http://t.cn/RUUefZa                             ","visitTimes":4,"result":"此微博称“上海市颛桥城管打死人了”不实，据@警民直通车-闵行 通报：市容管理人员葛路某准备骑电瓶车离开现场，被路边设摊人员黄某阻拦。黄某儿子葛树某驾驶一辆蓝色卡车撞向电瓶车，黄某被电瓶车带倒在地，当场头部出 血，后被送往医院经抢救无效死亡，并非城管打死人。详情：http://weibo.com/3236934434/DzDq3vS8K，被举报人言论构 成“发布不实信息”。现根据《微博社区管理规定》第19条，对被举报人处理如下：扣除信用积分2分。上述处理在公布后60分钟内生效。","publishTime":"2016-06-13 16:18"}
{"rumorCode":"K1CaN8wJg7a0d","title":"@无处安放大脸喵 举报@familiarwith范 不实信息","informerName":"无处安放大脸喵","informerUrl":"http://weibo.com/u/5198423515","rumormongerName":"familiarwith范","rumormongerUrl":"http://weibo.com/u/5641739274","rumorText":"上海市闵行区颛桥镇沪闵路向阳路，辛苦农民摆摊卖菜，恶意城管不分青红皂白掀摊打人致死，事后逃逸，120医生到场宣布死亡，家人痛苦万分，只求大家帮忙转发…（尤其上海的朋友）早日将黑心打人者绳之以法！！！ ","visitTimes":3,"result":"此微博称“上海市颛桥城管打死人了”不实，据@警民直通车-闵行 通报：市容管理人员葛路某准备骑电瓶车离开现场，被路边设摊人员黄某阻拦。黄某儿子葛树某驾驶一辆蓝色卡车撞向电瓶车，黄某被电瓶车带倒在地，当场头部出 血，后被送往医院经抢救无效死亡，并非城管打死人。详情：http://weibo.com/3236934434/DzDq3vS8K，被举报人言论构 成“发布不实信息”。现根据《微博社区管理规定》第19条，对被举报人处理如下：扣除信用积分2分。上述处理在公布后60分钟内生效。","publishTime":"2016-06-13 16:19"}
{"rumorCode":"K1CaN8wJg7aog","title":"@Steins_Brian 举报@侃爷不叫韦斯特 不实信息","informerName":"樱井卤面","informerUrl":"http://weibo.com/u/1823467132","rumormongerName":"侃爷不叫韦斯特","rumormongerUrl":"http://weibo.com/u/3177470652","rumorText":"        ：发现很多新闻都失效了，什么情况？为何不得公布？具体什么情况？这事能瞒得住吗？                             ","visitTimes":111,"result":"经查，此微博配图称“浦东机场...发生爆炸！巨响+蘑菇云！！！”不实，此事件爆炸并未产生蘑菇云。详情：http://weibo.com/2812231775/DzUw3my3R，被举报人言论夸大事实构成“发布不实信息”，且情节恶劣。现根据《微博社区管理规定》 （http://service.account.weibo.com/roles/guiding）第19条，对被举报人处理如下：扣除信用积分10分，禁言15天，禁被关注15天。上述处理在公布后60分钟内生效。","publishTime":"2016-06-12 21:56"}
{"rumorCode":"K1CaN8wJg7age","title":"@符号子_一只海獭 举报@猎奇菌 不实信息","informerName":"符号子_一只海獭","informerUrl":"http://weibo.com/u/1628520835","rumormongerName":"猎奇菌","rumormongerUrl":"http://weibo.com/u/5150931617","rumorText":"        ：[哆啦A梦吃惊]                             ","visitTimes":175,"result":"经查，该微博配图称“iPhone6S被偷，女生竟狂追2公里将小偷强暴”不实，经@重庆晨报 报道：男子偷体尖生手机，反遭狂追两公里被生擒；并未发生强暴事件。详情：http://weibo.com/1420157965/DyZdAjjju，被举报人构成“发布不实信息”，虽无即时危险，但应予澄清，现根据《微博社区管理规定》（http://service.account.weibo.com/roles/guiding）第19条，予以标识处理。","publishTime":"2016-06-13 16:28"}
{"rumorCode":"K1CaN8wJg7acj","title":"@隆闯天涯 举报@大怪兽的超人-Liu 不实信息","informerName":"隆闯天涯","informerUrl":"http://weibo.com/u/1842734325","rumormongerName":"大怪兽的超人-Liu","rumormongerUrl":"http://weibo.com/u/5641898585","rumorText":"急找孩子求转求帮忙 今天上午一个三岁多小女孩在世纪家园小区附近被人拐走了小女孩能说出她爸爸的手机号码 从监控上看是被一个四十多岁男人抱走了现大人都急疯了 有知情者请告之 万分感谢 看到信息的兄弟姐妹留意一下 联系人张静杰13759695559看到就转转吧 我们都会有孩子 谢谢你 http://t.cn/R2d2FKS ","visitTimes":7,"result":"经查，该微博称“有孩子被抢”不实，类似消息近两年在网上广为流传且都已经被当地警方辟谣，详情：http://weibo.com/2656274875/CodNboTCH，被举报人构成“发布不实信息”，虽无即时危险，但应予澄清，现根据《微博社区管理规定》 （http://service.account.weibo.com/roles/guiding）第19条，予以标识处理。 ","publishTime":"2016-06-13 17:02"}
{"rumorCode":"K1CaN8wJg7aci","title":"@隆闯天涯 举报@Shen小子 不实信息","informerName":"隆闯天涯","informerUrl":"http://weibo.com/u/1842734325","rumormongerName":"Shen小子","rumormongerUrl":"http://weibo.com/u/2598760037","rumorText":"求转，求帮忙！ 今天上午一个三岁多小女孩在世纪家园小区附近被人拐走了，小女孩能说出她爸爸的手机号码 从监控上看是被一个四十多岁男人抱走了现大人都急疯了 有知情者请告之 万分感谢 看到信息的兄弟姐妹留意一下 联系人 张静杰13759695559 看到就转转吧 我们都会有孩子 谢谢你 ","visitTimes":4,"result":"经查，该微博称“有孩子被抢”不实，类似消息近两年在网上广为流传且都已经被当地警方辟谣，详情：http://weibo.com/2656274875/CodNboTCH，被举报人构成“发布不实信息”，虽无即时危险，但应予澄清，现根据《微博社区管理规定》 （http://service.account.weibo.com/roles/guiding）第19条，予以标识处理。 ","publishTime":"2016-06-13 17:02"}
{"rumorCode":"K1CaN8wJg7ach","title":"@隆闯天涯 举报@吕途41268 不实信息","informerName":"隆闯天涯","informerUrl":"http://weibo.com/u/1842734325","rumormongerName":"吕途41268","rumormongerUrl":"http://weibo.com/u/5646571259","rumorText":"急找孩子，求转 实验 13930886687 帮忙扩散，今天上午一个三岁多小女孩在锦绣花园小区附近被人拐走了，小女孩能说出她爸爸的手机号码 从监控上看是被一个四十多岁男人抱走了现大人都急疯了 有知情者请告之 万分感谢 看到信息的兄弟姐妹留意一下 联系人 张静杰13930886687 http://t.cn/R2WJ2qX ","visitTimes":2,"result":"经查，该微博称“有孩子被抢”不实，类似消息近两年在网上广为流传且都已经被当地警方辟谣，详情：http://weibo.com/2656274875/CodNboTCH，被举报人构成“发布不实信息”，虽无即时危险，但应予澄清，现根据《微博社区管理规定》 （http://service.account.weibo.com/roles/guiding）第19条，予以标识处理。 ","publishTime":"2016-06-13 17:02"}
{"rumorCode":"K1CaN8wJg6K4i","title":"@APP前锋 举报@投资界摘要 不实信息","informerName":"APP前锋","informerUrl":"http://weibo.com/u/1963489217","rumormongerName":"投资界摘要","rumormongerUrl":"http://weibo.com/u/5108707133","rumorText":"【败光20亿，弄垮人民搜索，邓亚萍竟然要烧钱去教人创业？】败光20亿，弄垮人民搜索，邓亚萍竟然要烧钱去教人创业？,沉寂已久的邓亚萍重归大众视野，离开“国家队”转型体育创投。在此之前因为种种负面新闻已使她自带易黑体质。2013年即刻搜索被重组清算，邓败光20亿元的传闻爆 http://t.cn/R5ixd5l ","visitTimes":7,"result":"经查，所谓“邓亚萍即刻搜索败光20”等传言完全与事实不符，截止“20亿传闻”曝出前夕，即刻搜索自2010年5月成立至2013年2月，各年资金投入总量为5.09亿元，其中约85%的费用用于技术研发。详情：http://t.cn/R5IIgTn 。被举报人言论构成“发布不实信息”， 现根据《新浪微博社区管理规定》 （http://service.account.weibo.com/roles/guiding）第19条，对被举报人处理如下：扣除信用积分2分。上述处理在公布后60分钟内生效。","publishTime":"2016-06-13 17:31"}
{"rumorCode":"K1CaN8wJg6K4h","title":"@APP前锋 举报@北京纵横合力 不实信息","informerName":"APP前锋","informerUrl":"http://weibo.com/u/1963489217","rumormongerName":"北京纵横合力","rumormongerUrl":"http://weibo.com/u/2179970857","rumorText":"败光20亿，弄垮人民搜索，邓亚萍竟然要烧钱去教人创业？ - EZCapital 中国创业投资第一在线交流平台 沉寂已久的邓亚萍重归大众视野，离开“国家队”，转型体育创投。在此之前，因为种种负面新闻已使她自带易黑体质。这位曾经的乒乓皇后，退役后从运动员到博士、官员，她完成 http://t.cn/R5iE2Ld ","visitTimes":4,"result":"经查，所谓“邓亚萍即刻搜索败光20”等传言完全与事实不符，截止“20亿传闻”曝出前夕，即刻搜索自2010年5月成立至2013年2月，各年资金投入总量为5.09亿元，其中约85%的费用用于技术研发。详情：http://t.cn/R5IIgTn 。被举报人言论构成“发布不实信息”， 现根据《新浪微博社区管理规定》 （http://service.account.weibo.com/roles/guiding）第19条，对被举报人处理如下：扣除信用积分2分。上述处理在公布后60分钟内生效。","publishTime":"2016-06-13 17:33"}
{"rumorCode":"K1CaN8wJg6K4g","title":"@APP前锋 举报@电商头条 不实信息","informerName":"APP前锋","informerUrl":"http://weibo.com/u/1963489217","rumormongerName":"电商头条","rumormongerUrl":"http://weibo.com/u/2458565150","rumorText":"【败光20亿，弄垮公司，邓亚萍竟然要去教人创业？】互联网看重的是创新、产品、体验，而这些是政策给不了的，马云一开始也不懂互联网，但他是个商人，没有其他体制上的障碍，靠的不是国家是市场，正如有媒体人说：“邓亚萍做搜素引擎，难度跟李彦宏要拿乒乓世界冠军差不多！”http://t.cn/R5iZeqX ","visitTimes":158,"result":"经查，所谓“邓亚萍即刻搜索败光20”等传言完全与事实不符，截止“20亿传闻”曝出前夕，即刻搜索自2010年5月成立至2013年2月，各年资金投入总量为5.09亿元，其中约85%的费用用于技术研发。详情：http://t.cn/R5IIgTn 。被举报人言论构成“发布不实信息”， 现根据《新浪微博社区管理规定》 （http://service.account.weibo.com/roles/guiding）第19条，对被举报人处理如下：扣除信用积分2分。上述处理在公布后60分钟内生效。","publishTime":"2016-06-13 17:33"}
{"rumorCode":"K1CaN8wJg6K4f","title":"@APP前锋 举报@Bill王纯 不实信息","informerName":"APP前锋","informerUrl":"http://weibo.com/u/1963489217","rumormongerName":"Bill王纯","rumormongerUrl":"http://weibo.com/u/1528268017","rumorText":"        ：邓亚萍因个人创业原因离职，败光20亿，还是有限资金。第一次把大不要脸，说得那么小清新！[嘻嘻]            ","visitTimes":9,"result":"经查，所谓“邓亚萍即刻搜索败光20”等传言完全与事实不符，截止“20亿传闻”曝出前夕，即刻搜索自2010年5月成立至2013年2月，各年资金投入总量为5.09亿元，其中约85%的费用用于技术研发。详情：http://t.cn/R5IIgTn 。被举报人言论构成“发布不实信息”， 现根据《新浪微博社区管理规定》 （http://service.account.weibo.com/roles/guiding）第19条，对被举报人处理如下：扣除信用积分2分。上述处理在公布后60分钟内生效。","publishTime":"2016-06-13 17:37"}
{"rumorCode":"K1CaN8wJg6K4e","title":"@APP前锋 举报@蓝色帆都 不实信息","informerName":"APP前锋","informerUrl":"http://weibo.com/u/1963489217","rumormongerName":"蓝色帆都","rumormongerUrl":"http://weibo.com/u/1785370544","rumorText":"        ：【败光20亿，弄垮公司，邓亚萍竟然要去教人创业】 http://t.cn/R5iKneJ            ","visitTimes":4,"result":"经查，所谓“邓亚萍即刻搜索败光20”等传言完全与事实不符，截止“20亿传闻”曝出前夕，即刻搜索自2010年5月成立至2013年2月，各年资金投入总量为5.09亿元，其中约85%的费用用于技术研发。详情：http://t.cn/R5IIgTn 。被举报人言论构成“发布不实信息”， 现根据《新浪微博社区管理规定》 （http://service.account.weibo.com/roles/guiding）第19条，对被举报人处理如下：扣除信用积分2分。上述处理在公布后60分钟内生效。","publishTime":"2016-06-13 17:37"}'

require(stringr)
#str_match_all(read,'[\u4e00-\u9fa5]')

read1 = str_extract_all(read,'[\u4e00-\u9fa5]',simplify = T)
read2 = str_c(read1,sep='',collapse ='')
read2

#"rumorText":"

read1 = str_extract_all(read,'rumorText.+result',simplify = T) # 正确！
read2 = str_c(read1,sep='',collapse ='') # 正确！
read2 # 正确！

name = str_extract_all(string = web, pattern = '<span class="title">.+</span>')
movie.names_line <- unlist(name)

#readLines(read,encoding="UTF-8")

read1 = str_extract_all(read,'[\bs\S*?e\b]',simplify = T)
read2 = str_c(read1,sep='',collapse ='')
read2
'\bs\S*?e\b'
```

```{r}

library(readr)
rumorsdata <- read_csv("E:/data/rumor/rumorsdata.txt",col_names = F) 


```

