---
title: "B级三厢车用户洞察项目"
author: "宋骁"
date: "2019-7-18"
output:
  bookdown::html_document2:
    toc: true
    theme: united
slug: rusers
---

# 数据清理
  
## 变量
  
  + 人口学：性别`S5`； 年龄`S6__1__open`；婚姻状况`D5`；孩子`D6`；教育`D3`
  + 车系`S10B`
  + 车牌`S10`
  + 生活方式、价值观`Q7__1:Q7__35`
  + 对车的态度`A0__1:A0__27`


```{r a,message = F, comment = NA,warning = F,include = T,fig.align='center',out.width ='100%',fig.asp=0.7}
library(tidyverse)
dt.car <- read.csv("C:/Users/xsong/Desktop/table/DT.csv")
#knitr::kable((dt.car))
knitr::kable(prop.table(table(dt.car$S5))*100)
knitr::kable(prop.table(table(dt.car$D5))*100)
knitr::kable(prop.table(table(dt.car$D3))*100)
knitr::kable(prop.table(table(dt.car$S10B))*100)
knitr::kable(prop.table(table(dt.car$S10))*100)

ggplot(dt.car, aes(x = S6__1__open,fill=S10B)) + geom_histogram(density = 70) +
xlab('年龄') + 
ylab('频数') +
labs(fill="车型")


ggplot(dt.car, aes(S10B,S6__1__open)) + 
  geom_boxplot(size=0.1,outlier.colour ='sky blue',fill='sky blue') +
xlab('车型') + 
ylab('年龄') 
#thme(fill=guide_legend(title='车型'))
```



```{r b,message = F, comment = NA,warning = F,include = T,fig.align='center',out.width ='100%',fig.asp=0.7}
dt.car$S10B <- as.character(dt.car$S10B)
dta <- dt.car %>%
  select(S5,S6__1__open,D5,D6,D3,S10,S10B,Q7__1:Q7__35,A0__1:A0__27) %>% #筛选列
  rename(age=S6__1__open,edu=D3) %>% #重命名
  mutate(eduy=recode(edu,'初中'=9,
                     '大学本科 - 国内'=16,
                     '大学本科 - 国外'=16,
                     '大专'=15,
                     '高中'=12,
                     '技术/职业学校/中专'=12,
                     '研究生或以上 - 国内'=20),
         child=recode(D6,'没有孩子'=0,
                      '有1个孩子'=1,
                      '有2个孩子'=2,
                      '有3个孩子及以上'=3),
         S10=recode(S10,'奥迪-A4L'='豪华车',
                     '宝马-320Li'='豪华车',
                     '奔驰-C180'='豪华车'),
         S10B= ifelse(S10=='豪华车','豪华车',S10B) #将奔驰、宝马、奥迪编码为豪华车
         ) %>% #重编码
  select(edu,eduy,everything()) #排序

```

# 价值观变量的主成分分析
  + 

```{r c,message = F, comment = NA,warning = F,include = T,fig.align='center',out.width ='100%',fig.asp=0.7}
pcdata <- dta %>% #用于主成分分析的数据
  select(Q7__1:Q7__35) 

#循环编码35个变量
for(i in 1:35) {
  pcdata[,i+35] <- 0
  pcdata[,i+35][pcdata[,i]=='非常同意1'] <- 1
  pcdata[,i+35][pcdata[,i]=='比较同意2'] <- 2
  pcdata[,i+35][pcdata[,i]=='谈不上同不同意3'] <- 3
  pcdata[,i+35][pcdata[,i]=='比较不同意4'] <- 4
  pcdata[,i+35][pcdata[,i]=='完全不同意5'] <- 5
}

pcdata <- pcdata %>% #保留需要主成分分析的35个变量
  select(-(Q7__1:Q7__35)) 

#主成分分析
library(psych)
fa.parallel(pcdata, fa="pc", n.iter=100,show.legend=F, main="碎石图")
pc <- principal(pcdata, nfactors=3, rotate="varimax", score=T) #方差极大旋转
pc #三个主成分为PC1,PC2, PC3

rmd <- pc$scores #2个主成分为RC1,RC2
rmd <- as.data.frame(rmd)
rmd <- rmd %>% 
  rename(lfatd1=RC1,lfatd2=RC2,lfatd3=RC3)

dta <- cbind(dta,rmd)


```

# 对车的态度主成分分析

```{r d,message = F, comment = NA,warning = F,include = T,fig.align='center',out.width ='100%',fig.asp=0.7}

pcdata2 <- dta %>% #用于主成分分析的数据
  select(A0__1:A0__27) 

#循环编码27个变量
for(i in 1:27) {
  pcdata2[,i+27] <- 0
  pcdata2[,i+27][pcdata2[,i]=='非常同意1'] <- 1
  pcdata2[,i+27][pcdata2[,i]=='比较同意2'] <- 2
  pcdata2[,i+27][pcdata2[,i]=='谈不上同意不同意3'] <- 3
  pcdata2[,i+27][pcdata2[,i]=='比较不同意4'] <- 4
  pcdata2[,i+27][pcdata2[,i]=='完全不同意5'] <- 5
}

pcdata2 <- pcdata2 %>% #保留需要主成分分析的27个变量
  select(-(A0__1:A0__27)) 

#主成分分析
library(psych)
fa.parallel(pcdata2, fa="pc", n.iter=100,show.legend=F, main="碎石图")
pc2 <- principal(pcdata2, nfactors=3, rotate="varimax", score=T) #方差极大旋转
pc2
cwb <- pc2$scores #2个主成分为RC1,RC2
cwb <- as.data.frame(cwb)
cwb <- cwb %>% 
  rename(catatd1=RC1,catatd2=RC2,catatd3=RC3)

dta <- cbind(dta,cwb)

dta <- dta %>% 
  select(-(edu),-(D6),-(Q7__1:Q7__35),-(A0__1:A0__27),) %>% 
  mutate(child = ifelse(is.na(child)==T,0,child))

knitr::kable(head(dta,n=10),caption = '数据概要')


```


# 聚类分析

+ 聚成5类，使用变量：态度、价值观

```{r e,message = F, comment = NA,warning = F,include = T,fig.align='center',out.width ='100%',fig.asp=0.7}
cludta <- dta %>% 
  select(lfatd1,lfatd2,lfatd3,catatd1,catatd2,catatd3)

library(cluster) 
dta.scaled <- scale(cludta) #变量中心化
d <- dist(dta.scaled) #计算欧式距离
fit <- hclust(d, method="ward.D")
plot(fit, hang=-1, cex=.8, main="层次聚类图(使用Ward方法)",xlab='样本',ylab='高度')

rect.hclust(fit, k=4, border = "red")

```

+ 从上图可以看到有的类样本很多，有的很少。

+ 由于一些人口学特征，如性别等无法使用层次聚类法，现在使用相异度矩阵计算(Dissimilarity Matrix Calculation)法进行聚类。使用`cluster`包的`daisy`函数实现。

```{r f,message = F, comment = NA,warning = F,include = T,fig.align='center',out.width ='100%',fig.asp=0.7}
dta$S10B <- as.factor(dta$S10B)
gower_dist<-daisy(dta,metric = "gower")#分类变量的聚类
#summary(gower_dist)
h <- hclust(gower_dist)
plot(h,main = '层次聚类图(gower距离)',xlab='样本',ylab='高度')
rect.hclust(h, k=4, border = "red")

#提取最终的聚类方案
dta$clusters <- cutree(h, k=4)
knitr::kable(table(dta$clusters),caption = '每一类的样本量',align='c')
```

+ 此方法聚类样本较为均衡。

## 聚类分析后的描述性统计

```{r g,message = F, comment = NA,warning = F,include = T,fig.align='center',out.width ='100%',fig.asp=0.7}

knitr::kable(
dta %>%
group_by(clusters) %>%
summarize(平均年龄 = mean(age),
           平均教育年限 = mean(eduy),
           平均子女数 = mean(child)),digits=2,caption='分聚类类别描述性统计',align='c')

mar <- table(dta$D5,dta$clusters)
names(dimnames(mar))<-c("婚姻状况","聚类类别")
knitr::kable(mar,caption = '聚类类别和婚姻状况的交互表')
#矩阵小标题
mar <- as.data.frame(mar)
ggplot(mar,aes(聚类类别,婚姻状况)) +
  geom_tile(aes(fill=Freq),color='black') +
  scale_fill_gradient(low='white',high = 'steel blue')+
  geom_text(aes(label = Freq))+ #图中加入频数
labs(fill="频数")

knitr::kable(table(dta$S10B,dta$clusters),caption = '聚类类别和车系的交互表')
mar <- table(dta$S10B,dta$clusters)
names(dimnames(mar))<-c("车系","聚类类别")
mar <- as.data.frame(mar)
ggplot(mar,aes(聚类类别,车系)) +
  geom_tile(aes(fill=Freq),color='black') +
  scale_fill_gradient(low='white',high = 'steel blue')+
  geom_text(aes(label = Freq))+ #图中加入频数
labs(fill="频数")

knitr::kable(table(dta$S5,dta$clusters),caption = '聚类类别和性别的交互表')
mar <- table(dta$S5,dta$clusters)
names(dimnames(mar))<-c("性别","聚类类别")
mar <- as.data.frame(mar)
ggplot(mar,aes(聚类类别,性别)) +
  geom_tile(aes(fill=Freq),color='black') +
  scale_fill_gradient(low='white',high = 'steel blue')+
  geom_text(aes(label = Freq))+ #图中加入频数
labs(fill="频数")



```



# 多分类决策树

```{r h,message = F, comment = NA,warning = F,include = T,echo=F,fig.align='center',out.width ='100%',fig.asp=1,fig.cap='多分类决策树'}
library(rpart)
library(rpart.plot)

cont <- rpart.control(minsplit=5,maxcompete=100,xval=10,maxdepth=30,cp=0.014) #设置参数
tree.fit <- rpart(clusters ~ eduy+S5+age+ D5+S10B+child+lfatd1+lfatd2+lfatd3	+catatd1+catatd2,data = dta,method = "class",parms = list(split="gini"),control=cont,na.action = na.omit)

knitr::kable(tree.fit$cptable,caption = '复杂度参数表')
#决策树
rpart.plot(tree.fit)

```





