---
title: 'SQL增删改查'
author: "宋骁"
date: '2019-08-25'
slug: sql
---




---

[MySQL安装(基于Windows)](https://www.cnblogs.com/vuenote/archive/2018/10/13/9783463.html)

[MySQL 教程](http://www.runoob.com/mysql/mysql-tutorial.html)

[廖雪峰SQL教程](https://www.liaoxuefeng.com/wiki/1177760294764384)

[W3school SQL教程](https://www.w3school.com.cn/sql/index.asp)

---

+ 数据：[NBA技术统计](https://www.kaggle.com/drgilermo/nba-players-stats)和[球员薪酬](https://www.kaggle.com/koki25ando/salary)数据，如果一名球员在同一个赛季辗转多只球队，就会产生多行记录。

+ 本文基于MySQL。此外建议尝试使用SQLite。SQLite是长期以来被低估的数据库：它开源、体积小、和Python与R等编程语言的交互性好。它不需要设置数据驱动。而且SQLite数据的储存只使用一个数据库文件，适用于多表管理。但是不同的SQL数据库语法略有区别。

+ SQLite文件见[这里](https://www.kaggle.com/rikdifos/nba-salary-and-statistics-201617)

# 变量排序

```sql
SELECT salary17_18,Player 
FROM salary 
ORDER BY salary17_18 DESC;
```

# 删除 & 增添列 
```sql
ALTER TABLE salary 
DROP COLUMN Tm
ADD COLUMN Team VARCHAR;
```

# 重编码新变量

```sql
ALTER TABLE salary 
ADD salary17_18 FLOAT;
UPDATE salary SET salary17_18 = season17_18/1000000
```
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg .tg-lboi{border-color:inherit;text-align:left;vertical-align:middle}
.tg .tg-0pky{border-color:inherit;text-align:left;vertical-align:top}
</style>
<table class="tg">
  <tr>
    <th class="tg-lboi">f1</th>
    <th class="tg-lboi">Player</th>
    <th class="tg-lboi">Tm</th>
    <th class="tg-0pky">season17_18</th>
    <th class="tg-0pky">salary17_18</th>
  </tr>
  <tr>
    <td class="tg-lboi">1</td>
    <td class="tg-lboi">Stephen Curry</td>
    <td class="tg-lboi">GSW</td>
    <td class="tg-0pky">34682550</td>
    <td class="tg-0pky">34.6825</td>
  </tr>
  <tr>
    <td class="tg-lboi">2</td>
    <td class="tg-lboi">LeBron James</td>
    <td class="tg-lboi">CLE</td>
    <td class="tg-0pky">33285709</td>
    <td class="tg-0pky">33.2857</td>
  </tr>
  <tr>
    <td class="tg-0pky">3</td>
    <td class="tg-0pky">Paul Millsap</td>
    <td class="tg-0pky">DEN</td>
    <td class="tg-0pky">31269231</td>
    <td class="tg-0pky">31.2692</td>
  </tr>
  <tr>
    <td class="tg-0pky">4</td>
    <td class="tg-0pky">Gordon Hayward</td>
    <td class="tg-0pky">BOS</td>
    <td class="tg-0pky">29727900</td>
    <td class="tg-0pky">29.7279</td>
  </tr>
  <tr>
    <td class="tg-0pky">5</td>
    <td class="tg-0pky">Blake Griffin</td>
    <td class="tg-0pky">DET</td>
    <td class="tg-0pky">29512900</td>
    <td class="tg-0pky">29.5129</td>
  </tr>
</table>

# 按特定行删除重复值

+ `DISTINCT`按选中的列去重。得到高龄球员榜

```sql
SELECT DISTINCT Player,Age 
FROM seasons 
ORDER BY Age DESC;
```
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg .tg-cly1{text-align:left;vertical-align:middle}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg">
  <tr>
    <th class="tg-cly1">Player</th>
    <th class="tg-cly1">Age</th>
  </tr>
  <tr>
    <td class="tg-cly1">Kevin Willis</td>
    <td class="tg-cly1">44</td>
  </tr>
  <tr>
    <td class="tg-cly1">Robert Parish*</td>
    <td class="tg-cly1">43</td>
  </tr>
  <tr>
    <td class="tg-0lax">Dikembe Mutombo*</td>
    <td class="tg-0lax">42</td>
  </tr>
  <tr>
    <td class="tg-0lax">Kevin Willis</td>
    <td class="tg-0lax">42</td>
  </tr>
  <tr>
    <td class="tg-0lax">Robert Parish*</td>
    <td class="tg-0lax">42</td>
  </tr>
</table>

```sql
SELECT pubid,adfmt,event,COUNT(DISTINCT imei),COUNT(DISTINCT idfa) FROM table_numb 
WHERE pubid= '20' AND adfmt <> 'chip' AND event = 'ac'
```



# 按条件筛选数据

+ 使用`WHERE`子句保留2017年之后的数据

```sql
SELECT * 
FROM seasons 
WHERE Year>=2017
```
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg .tg-cly1{text-align:left;vertical-align:middle}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg">
  <tr>
    <th class="tg-cly1">f1</th>
    <th class="tg-cly1">Year</th>
    <th class="tg-0lax">Player</th>
    <th class="tg-0lax">Pos</th>
    <th class="tg-0lax">Age</th>
    <th class="tg-0lax">Tm</th>
    <th class="tg-0lax">G</th>
    <th class="tg-0lax">GS</th>
    <th class="tg-0lax">MP</th>
    <th class="tg-0lax">PER</th>
    <th class="tg-0lax">TS%</th>
  </tr>
  <tr>
    <td class="tg-cly1">24096</td>
    <td class="tg-cly1">2017</td>
    <td class="tg-0lax">Alex Abrines</td>
    <td class="tg-0lax">SG</td>
    <td class="tg-0lax">23</td>
    <td class="tg-0lax">OKC</td>
    <td class="tg-0lax">68</td>
    <td class="tg-0lax">6</td>
    <td class="tg-0lax">1055</td>
    <td class="tg-0lax">10.1</td>
    <td class="tg-0lax">0.56</td>
  </tr>
  <tr>
    <td class="tg-cly1">24097</td>
    <td class="tg-cly1">2017</td>
    <td class="tg-0lax">Quincy Acy</td>
    <td class="tg-0lax">PF</td>
    <td class="tg-0lax">26</td>
    <td class="tg-0lax">TOT</td>
    <td class="tg-0lax">38</td>
    <td class="tg-0lax">1</td>
    <td class="tg-0lax">558</td>
    <td class="tg-0lax">11.8</td>
    <td class="tg-0lax">0.565</td>
  </tr>
  <tr>
    <td class="tg-0lax">24098</td>
    <td class="tg-0lax">2017</td>
    <td class="tg-0lax">Quincy Acy</td>
    <td class="tg-0lax">PF</td>
    <td class="tg-0lax">26</td>
    <td class="tg-0lax">DAL</td>
    <td class="tg-0lax">6</td>
    <td class="tg-0lax">0</td>
    <td class="tg-0lax">48</td>
    <td class="tg-0lax">-1.4</td>
    <td class="tg-0lax">0.355</td>
  </tr>
  <tr>
    <td class="tg-0lax">24099</td>
    <td class="tg-0lax">2017</td>
    <td class="tg-0lax">Quincy Acy</td>
    <td class="tg-0lax">PF</td>
    <td class="tg-0lax">26</td>
    <td class="tg-0lax">BRK</td>
    <td class="tg-0lax">32</td>
    <td class="tg-0lax">1</td>
    <td class="tg-0lax">510</td>
    <td class="tg-0lax">13.1</td>
    <td class="tg-0lax">0.587</td>
  </tr>
  <tr>
    <td class="tg-0lax">24100</td>
    <td class="tg-0lax">2017</td>
    <td class="tg-0lax">Steven Adams</td>
    <td class="tg-0lax">C</td>
    <td class="tg-0lax">23</td>
    <td class="tg-0lax">OKC</td>
    <td class="tg-0lax">80</td>
    <td class="tg-0lax">80</td>
    <td class="tg-0lax">2389</td>
    <td class="tg-0lax">16.5</td>
    <td class="tg-0lax">0.589</td>
  </tr>
</table>

# 数据合并

## 横向连接

```sql
ALTER TABLE salary
DROP COLUMN Tm;
SELECT * FROM salary
JOIN seasons
ON salary.Player=seasons.Player
```
+ MySQL多对一、一对多匹配可以自动复制。



## 纵向连接
 
 + `UNION ALL`允许重复值
 + `UNION`不允许重复值
 
```sql
SELECT Player FROM salary
UNION ALL
SELECT Player FROM seasons; 
ORDER BY Player
```
# 按条件删除行

+ 删除斯蒂芬·库里

+ `LIMIT`语句控制结果显示的行数

```sql
DELETE FROM salary 
WHERE Player='Stephen Curry';
SELECT * FROM salary LIMIT 5
```
<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg .tg-cly1{text-align:left;vertical-align:middle}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg">
  <tr>
    <th class="tg-cly1">f1</th>
    <th class="tg-cly1">Player</th>
    <th class="tg-cly1">season17_18</th>
    <th class="tg-0lax">salary17_18</th>
  </tr>
  <tr>
    <td class="tg-cly1">2</td>
    <td class="tg-cly1">LeBron James</td>
    <td class="tg-cly1">33285709</td>
    <td class="tg-0lax">33.2857</td>
  </tr>
  <tr>
    <td class="tg-cly1">3</td>
    <td class="tg-cly1">Paul Millsap</td>
    <td class="tg-cly1">31269231</td>
    <td class="tg-0lax">31.2692</td>
  </tr>
  <tr>
    <td class="tg-0lax">4</td>
    <td class="tg-0lax">Gordon Hayward</td>
    <td class="tg-0lax">29727900</td>
    <td class="tg-0lax">29.7279</td>
  </tr>
  <tr>
    <td class="tg-0lax">5</td>
    <td class="tg-0lax">Blake Griffin</td>
    <td class="tg-0lax">29512900</td>
    <td class="tg-0lax">29.5129</td>
  </tr>
  <tr>
    <td class="tg-0lax">6</td>
    <td class="tg-0lax">Kyle Lowry</td>
    <td class="tg-0lax">28703704</td>
    <td class="tg-0lax">28.7037</td>
  </tr>
</table>


# 视图

+ 在SQL中，视图是基于SQL语句的结果集的可视化的表。

```sql
CREATE VIEW teamage AS
SELECT DISTINCT Year,Tm, AVG(Age)
FROM season
GROUP BY Tm
ORDER BY Year;
```

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{font-family:Arial, sans-serif;font-size:14px;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg th{font-family:Arial, sans-serif;font-size:14px;font-weight:normal;padding:10px 5px;border-style:solid;border-width:1px;overflow:hidden;word-break:normal;border-color:black;}
.tg .tg-cly1{text-align:left;vertical-align:middle}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg">
  <tr>
    <th class="tg-cly1">f1</th>
    <th class="tg-cly1">Player</th>
    <th class="tg-cly1">season17_18</th>
    <th class="tg-0lax">salary17_18</th>
  </tr>
  <tr>
    <td class="tg-cly1">2</td>
    <td class="tg-cly1">LeBron James</td>
    <td class="tg-cly1">33285709</td>
    <td class="tg-0lax">33.2857</td>
  </tr>
  <tr>
    <td class="tg-cly1">3</td>
    <td class="tg-cly1">Paul Millsap</td>
    <td class="tg-cly1">31269231</td>
    <td class="tg-0lax">31.2692</td>
  </tr>
  <tr>
    <td class="tg-0lax">4</td>
    <td class="tg-0lax">Gordon Hayward</td>
    <td class="tg-0lax">29727900</td>
    <td class="tg-0lax">29.7279</td>
  </tr>
  <tr>
    <td class="tg-0lax">5</td>
    <td class="tg-0lax">Blake Griffin</td>
    <td class="tg-0lax">29512900</td>
    <td class="tg-0lax">29.5129</td>
  </tr>
  <tr>
    <td class="tg-0lax">6</td>
    <td class="tg-0lax">Kyle Lowry</td>
    <td class="tg-0lax">28703704</td>
    <td class="tg-0lax">28.7037</td>
  </tr>
</table>

从视图中查询:

```sql
SELECT COUNT(DISTINCT Tm) 
FROM teamage;
```

# 空值的处理

来一道简单的Leecode题

某网站包含两个表，Customers 表和 Orders 表。编写一个 SQL 查询，找出所有从不订购任何东西的客户。

Customers 表：

```
+----+-------+
| Id | Name  |
+----+-------+
| 1  | Joe   |
| 2  | Henry |
| 3  | Sam   |
| 4  | Max   |
+----+-------+
```
Orders 表：

```
+----+------------+
| Id | CustomerId |
+----+------------+
| 1  | 3          |
| 2  | 1          |
+----+------------+
```
例如给定上述表格，你的查询应返回：

```
+-----------+
| Customers |
+-----------+
| Henry     |
| Max       |
+-----------+
```


```sql
SELECT L1.Name AS Customers
FROM Customers AS L1
LEFT JOIN Orders ON Orders.CustomerId = L1.Id
WHERE Orders.CustomerId IS NULL;
```

> 只能采用IS NULL或IS NOT NULL，而不能采用=, <, <>, !=这些操作符来判断NULL

# 多表联结

> 遇事不决，多表联结 
———— 沃茨基·硕德

来道力扣题：

选出所有 bonus < 1000 的员工的 name 及其 bonus。

Employee 表单
```
+-------+--------+-----------+--------+
| empId |  name  | supervisor| salary |
+-------+--------+-----------+--------+
|   1   | John   |  3        | 1000   |
|   2   | Dan    |  3        | 2000   |
|   3   | Brad   |  null     | 4000   |
|   4   | Thomas |  3        | 4000   |
+-------+--------+-----------+--------+
```
empId 是这张表单的主关键字
Bonus 表单
```
+-------+-------+
| empId | bonus |
+-------+-------+
| 2     | 500   |
| 4     | 2000  |
+-------+-------+
```
empId 是这张表单的主关键字
输出示例：
```
+-------+-------+
| name  | bonus |
+-------+-------+
| John  | null  |
| Dan   | 500   |
| Brad  | null  |
+-------+-------+
```
答案：

```sql
# Write your MySQL query statement below
SELECT name, bonus
FROM Employee
LEFT JOIN Bonus ON Employee.empId =  Bonus.empId
WHERE Bonus.bonus < 1000 OR Bonus.bonus IS NULL;
```


# FROM子查询

FROM子查询把内层的查询结果当成临时表，供外层sql再次查询。查询结果集可以当成表看待。临时表要使用一个别名。
```
+--------------+---------+
| Column Name  | Type    |
+--------------+---------+
| player_id    | int     |
| device_id    | int     |
| event_date   | date    |
| games_played | int     |
+--------------+---------+
```
(player_id, event_date) 是这个表的两个主键
这个表显示的是某些游戏玩家的游戏活动情况
每一行是在某天使用某个设备登出之前登录并玩多个游戏（可能为0）的玩家的记录
请编写一个 SQL 查询，描述每一个玩家首次登陆的设备名称

查询结果格式在以下示例中：

Activity table:
```
+-----------+-----------+------------+--------------+
| player_id | device_id | event_date | games_played |
+-----------+-----------+------------+--------------+
| 1         | 2         | 2016-03-01 | 5            |
| 1         | 2         | 2016-05-02 | 6            |
| 2         | 3         | 2017-06-25 | 1            |
| 3         | 1         | 2016-03-02 | 0            |
| 3         | 4         | 2018-07-03 | 5            |
+-----------+-----------+------------+--------------+
```
Result table:
```
+-----------+-----------+
| player_id | device_id |
+-----------+-----------+
| 1         | 2         |
| 2         | 3         |
| 3         | 1         |
+-----------+-----------+
```
解答：
```sql
/* # 原答案
SELECT player_id, device_id
FROM Activity 
WHERE event_date in(SELECT min(event_date) FROM Activity GROUP BY  player_id);
*/

SELECT player_id, device_id
FROM Activity 
WHERE (player_id, event_date) IN (SELECT player_id, min(event_date) FROM Activity GROUP BY  player_id);
```

# 条件判断的运用

一个小学生 Tim 的作业是判断三条线段是否能形成一个三角形。

然而，这个作业非常繁重，因为有几百组线段需要判断。

假设表 triangle 保存了所有三条线段的三元组 x, y, z ，你能帮 Tim 写一个查询语句，来判断每个三元组是否可以组成一个三角形吗？

```
| x  | y  | z  |
|----|----|----|
| 13 | 15 | 30 |
| 10 | 20 | 15 |
```

对于如上样例数据，你的查询语句应该返回如下结果：

```
| x  | y  | z  | triangle |
|----|----|----|----------|
| 13 | 15 | 30 | No       |
| 10 | 20 | 15 | Yes      |
```

```sql
SELECT x, y, z, (CASE WHEN x + y > z 
AND x + z > y 
AND z + y > x 
THEN 'Yes' ELSE 'No' END) AS triangle
FROM triangle;

SELECT x, y, z, IF (x+y>z 
AND x+z>y 
AND y+z>x, 'Yes', 'No') AS triangle 
FROM triangle;
```

`IF` 用法类似于R语言的`ifelse()`函数。







